### ISSUE TITLE
Infinite loop when loading wizard mode save

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#101]
Steps to reproduce:
1. Start new game.
2. Activate wizard mode.
3. Enter any area.
4. Quit, but answer no to "Remove saves?".
5. Load the save that's named after your character (i.e. not the AutoSave), either via "Start game" or "Continue game".
6. The game starts looping infinitely in [this loop](https://github.com/Attnam/ivan/blob/2783eacef86185cdfe0bdbeb86ea0389641ea7db/Main/Source/game.cpp#L421), with `InWilderness = true`.

If you activate wizard mode _after_ entering an area, this doesn't happen.

**Comment by fejoa** [comment]
I think it is also true that if you activate wizard mode in a level area and then quit in the world map then you get the same problem.
