### ISSUE TITLE
ESP behaving like infravision?

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#109]
I ate a floating eye corpse and got temporary ESP. I don't have anything granting me Infravision. Should I be able to see this snake?

![esp](https://cloud.githubusercontent.com/assets/2760420/14066656/f4924e08-f414-11e5-8f06-8b7b6e7e5b01.png)

**Comment by andrewtweber** [comment]
Actually.. snakes aren't even warm blooded. But it's basically letting me see all creatures

**Comment by fejoa** [comment]
Conditions for seeing monsters by ESP are tested here: https://github.com/Attnam/ivan/blob/master/Main/Source/char.cpp#L5039
The idea is that anything with a brain or a central nervous system (INT >= 5) should be able to be seen.
So things like golems, mommos, skeletons or even [the pure mass of bill's will](https://www.reddit.com/r/technology/comments/4brgvm/microsofts_teen_girl_ai_tay_turns_into_a/) - i.e. things with no brain, or a disembodied brain, can't be seen.

**Comment by andrewtweber** [comment]
Ok thanks. I thought it was just "intelligent" creatures, not anything with a brain
