### ISSUE TITLE
Crash on 'C'hatting with neutral Ivan

### ISSUE THREAD

**Issue by serin-delaunay** [Attnam/ivan#119]
In 5.0.5, if I go to Ivan's level and chat with him, the game halts for a second then crashes. If I tame him with conventional means and then talk to him, he responds and the game continues as normal.

**Comment by fejoa** [comment]
That's rather worrisome because I didn't know that changes we have made so far would affect something as basic as that. Do you have an autosave file, or is it reproducible in wizard mode?

**Comment by serin-delaunay** [comment]
I believe I've encountered it in wizmode too. I don't have any normal saves that have reached Ivan yet.

**Comment by fejoa** [comment]
Ok, this should be pretty easy to debug. I'll try check it out as soon as I can. Hopefully it uncovers clues about related bugs that have come up. Seems like this is a fairly isolated case though.
