### ISSUE TITLE
Crash on becoming very hungry while digging

### ISSUE THREAD

**Issue by serin-delaunay** [Attnam/ivan#120]
If I'm hungry, start digging a wall, and become very hungry before finishing, the game asks me whether I want to continue. at this prompt, some keypresses cause the game to crash.

**Comment by fejoa** [comment]
Ok so I verified this causes a crash when pressing keys other than y or n. I'll look into fixing this as soon as possible.

**Comment by fejoa** [comment]
I can no longer reproduce this bug in the latest build. @serin-delaunay can you verify that this is fixed for `0.50.8`?

**Comment by emlai** [comment]
Reproduced on current master. Stack trace:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ivan                          	0x000000010a602737 dig::Handle() + 951 (actions.cpp:279)
1   ivan                          	0x000000010a61eac6 character::Be() + 966 (char.cpp:905)
2   ivan                          	0x000000010a6d65d0 pool::Be() + 48 (pool.cpp:33)
3   ivan                          	0x000000010a723a70 game::Run() + 1056 (game.cpp:612)
4   ivan                          	0x000000010a811fc6 main + 1158 (main.cpp:94)
5   libdyld.dylib                 	0x00007fffe5ede235 start + 1
```

**Comment by fejoa** [comment]
Bother. The player must therefore have a parasite digging up his intestines at the same time as he is digging the tunnel walls.
