### ISSUE TITLE
Elided double letters in science talking compoundnouns

### ISSUE THREAD

**Issue by serin-delaunay** [Attnam/ivan#122]
When the science talking system puts together a noun prefix and a noun, sometimes the last letter of the prefix matches the first letter of the noun and the double letter is deleted. There are presumably some cases where this makes sense, but as a native speaker I would generally find the constructions with double letters more natural.

A totally unscientific cherry-picked example would be "metalgorithms". Comparison of the singular form using [Google Fight](http://www.googlefight.co.uk/metalgorithm-vs-metaalgorithm.php) shows "metaalgorithm" to be favoured over "metalgorithm".

**Comment by serin-delaunay** [comment]
On the subject of spelling, there are still a few errors here and there, but it's probably more efficient to skip the issue report process and just make pullrequests for them.
I seem to remember spotting some inconsistencies in the game's overall US English presentation, but looking again I can only find them in the developer's notes and class/method identifiers, where they aren't doing any harm.
It is strange that the game uses US English and metric weights - perhaps the Attnamese Empire is what results aafter the USA adopts the metric system?

**Comment by andrewtweber** [comment]
Yes I would say skip the Issue and just submit a PR. I believe a lot of the in-game ones were fixed in a recent PR
