### ISSUE TITLE
Dwarves missing part of their body

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#143]
In the current master branch, kamikaze dwarves look like this:

<img width="79" alt="screen shot 2016-06-26 at 12 52 26" src="https://cloud.githubusercontent.com/assets/7543552/16361557/3156a8c8-3b9d-11e6-85ed-acc57569d198.png">

There's something missing below their belt.

Might be related to #66.

**Comment by fejoa** [comment]
I noticed the same lately. This felt like so long ago. I'll try and have a look at what parts of the graphic file were changed to see if it can be fixed this way.

**Comment by fejoa** [comment]
Hmm, I downloaded https://github.com/fejoa/ivan/blob/03de372f435a2fb0cb39e4d732f10e1d2e1a5ea7/Graphics/Humanoid.pcx. Somewhere between it had been changed back, giving the missing midriff problem. Pity we can't "diff" the graphics files :laughing:

**Comment by emlai** [comment]
> Pity we can't "diff" the graphics files

Hmm, actually, GitHub does allow diffing certain image formats, see https://help.github.com/articles/rendering-and-diffing-images/.

PNG, JPG, GIF, PSD, and SVG are supported. Should we convert the PCX files to PNG or GIF? Could be worth it…

**Comment by fejoa** [comment]
I sent GitHub an email asking them if they have plans to include PCX file format in their diff tool. Then we can decide. 
It would be handy to make the change. The only trouble might be that the PCX files themselves contain information about the colour palette in their headers, and IVAN makes use of this capability by specifying exactly what those 256 colours are. 
Looking at wikipedia, I suppose PNG supports palette information as well. Might be worth it if GitHub say they don't do PCX...

**Comment by fejoa** [comment]
So I got a reply from github not long after I sent them an e-mail. They said this:

```
Thanks for getting in touch! I can definitely see how diffing .pcx files could be helpful for your project. It looks like this might be an older file format, so I'm not sure if the team currently plans on supporting this. However, we do consider every suggestion we receive and I'll pass this on to our team! I can't promise if or when we would support PCX, but your feedback has been heard!

Please let me know if you have any other questions!

Cheers,

GitHub Support
```

So the short answer is no. I read the wikipedia entry on png format, and it looks like it can accomodate palette information. We would need to accomodate 256 colours, which png affords. I think it would be worth a try if it makes it possible to perform a diff on github.

**Comment by emlai** [comment]
Okay, I'll make an issue for that.
