### ISSUE TITLE
Minor install bug

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#148]
I had checked out the `XinrochTomb` branch and run `make install` which installed Xinroch's script file in /usr/local/share

After switching back to `master` and recompiling, running `make install` copies all the scripts but does not delete any obsolete ones.

Starting a new game resulted in a crash with this error message:

`Odd numeric value "XINROCH_TOMB" encountered in file /usr/local/share/ivan/Script/dungeons/XinrochTomb.dat, line 22!`

Obviously an easy fix to simply remove that file, and unlikely to affect anyone except devs, but would be nice to fix.

**Comment by emlai** [comment]
Another workaround is to <code>sudo make <strong>un</strong>install</code> the version with `XinrochTomb.dat` before running `make install` on `master` again. This should remove all the files that `make install` copied to the `Script` directory.

**Comment by andrewtweber** [comment]
Oooh ok never mind then.
