### ISSUE TITLE
Convert build system to CMake?

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#149]
The current Autotools build system is a bit old and clunky. A more modern solution such as CMake would provide many benefits. It's also what most C++ projects are using nowadays.

The main advantage is that CMake is not a build system, but a build system _generator_. It can generate Makefiles, various IDE projects, and other build systems. This is very convenient, since it allows everyone to work in a way that best suits their workflow.

Many more reasons for and against are already listed on the web, so I won't repeat them here. Here are a few links:

http://stackoverflow.com/a/18291580/3425536
http://stackoverflow.com/q/5837764/3425536
https://www.quora.com/Is-it-worth-replacing-autotools-with-cmake

What do you think?

(I could do this.)

**Comment by fejoa** [comment]
I'm convinced :)

**Comment by emlai** [comment]
Great! I'll get on to it.
