### ISSUE TITLE
Too easy to get permanent Telecontrol and ESP

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#163]
Conversation here: https://attnam.com/posts/26800

#162

**Comment by emlai** [comment]
Fixed in #162.

**Comment by andrewtweber** [comment]
Not a fan of this change :( 

In the past, a savvy player who knows the dev's attention to detail could figure it out. Or (like I did), a player could accidentally give themselves a permanent state and then later retrace their steps and figure out how they got it. I think that with this change it is now a 0% chance that any new player will discover this on their own without reading the forum/wiki

**Comment by fejoa** [comment]
Let's just roll this back: #171
