### ISSUE TITLE
Move dwarf graphics down by 1 pixel

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#169]
Currently they look like this:
<img width="256" alt="before" src="https://cloud.githubusercontent.com/assets/7543552/18417984/a2c857f0-7846-11e6-9035-586250128d75.png">

After moving down by 1 pixel:
<img width="256" alt="after" src="https://cloud.githubusercontent.com/assets/7543552/18417986/a7130256-7846-11e6-9261-83a2553e8e4c.png">

There appear to be some issues in implementing this, see https://github.com/Attnam/ivan/pull/164#issuecomment-246294939 for details.

**Comment by red-kangaroo** [comment]
This can be closed. :)
