### ISSUE TITLE
Lanterns causing fires

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#17]
Smashing lanterns should be a source of fire initiation

**Comment by AlexMooney** [comment]
Are we calling this one done, or, if not, can we add a list of stuff we want to add to finish this?

**Comment by fejoa** [comment]
Yeah, it's pretty much done. I think the fire subsystem is pretty well fleshed out. There are still bugs to catch and there are other subsystems to keep working on. If need be, the fire subsystem can be revisited at a later date.
