### ISSUE TITLE
Intoduce burning bodyparts

### ISSUE THREAD

**Issue by rvanherel** [Attnam/ivan#18]
Burning bodyparts
Burning zombies
Burning skeletons
Burning golems

**Comment by rvanherel** [comment]
A start has been made here: baa8993917ccbbeb5186e925a5723db691ec3ecc
Burning skeletons and golems are possible, but zombies are unlikely

**Comment by rvanherel** [comment]
See this and later commits: https://github.com/Attnam/ivan/commit/75ca799e90092bf857b3af0846ed104aeb089145

**Comment by andrewtweber** [comment]
Do artificial material limbs burn as well, such as if you had the misfortune of getting a parchment limb?
