### ISSUE TITLE
Undead based on strong monsters spawn too early

### ISSUE THREAD

**Issue by serin-delaunay** [Attnam/ivan#185]
In 0.50.5+, a lot of my runs have been ended in UT by zombies and skeletons based on powerful monsters. These have included an orc squad leader zombie, a skeleton of an elder dark mage (which was invisible for some reason), a zombie of a high-level mistress (can't remember which type), and countless veteran kamikaze dwarf zombies/skeletons. Some of these have spawned in UT1 before I've picked up any equipment, and most of them are powerful enough to stomp a typical character that reaches GC1.

I think these monsters spawn at low enough danger levels for the resulting imbalance to be considered a bug.

**Comment by fejoa** [comment]
Undead configs are created here: https://github.com/Attnam/ivan/blob/master/Main/Source/char.cpp#L5904

Maybe we can change the way the base attributes are modified for each undead configuration?

**Comment by andrewtweber** [comment]
Is it possible to only spawn undead versions of the living monsters that are spawning?

**Comment by serin-delaunay** [comment]
Restricting undead spawns to those based on living monsters that are spawning might be overkill - there are a lot of monsters who shouldn't spawn for a given danger level, but whose undead versions are weak enough to be appropriate.
Still, unless undead are somehow bypassing the danger system, that might be the simplest fix.

**Comment by AlexMooney** [comment]
The chameleons also have an annoying tendency to polymorph into high level ghosts, which is likely related to this.  Somehow the undead are not getting a very fair danger level evaluation.

**Comment by andrewtweber** [comment]
I don't think the chameleons are necessarily related. They often polymorph into high level golems, etc. I think chameleons just polymorph into anything

**Comment by andrewtweber** [comment]
I might be imagining it but this seems improved. I've still encountered zombies of what were once powerful monsters, but they're not as dangerous

**Comment by red-kangaroo** [comment]
I have yet to encounter an out-of-depth undead in 0.50.9, too. Zombies of master necromancers or mages still appear, but they are not actually dangerous - without their magic, they have quite low stats. So it seems to be working right, for whatever reason.

**Comment by andrewtweber** [comment]
Actually right after posting the above comment, I did encounter one. And I've still encountered a couple here and there. Hoping that fejoa's PR will fix this. For now I'm going to close this issue and we can reopen if it's still a problem
