### ISSUE TITLE
CMake: add some missing libraries for building windows exe

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#188]
Need to add `-static-libgcc -static-libstdc++` after `-lmingw32 -lSDL2main -lSDL2` etcetera

**Comment by emlai** [comment]
Everything seems to work fine without these. Are they actually required?  And if so, should they be used for all SDL2 MinGW projects (in which case they should go to `FindSDL2.cmake`), or are they only IVAN-specific (in which case they should go to `FeLib/CMakeLists.txt`)?

**Comment by fejoa** [comment]
If I compile straight out of the box on Windows I can always run the game because I have the relevant libraries installed on my path. If I compile a binary out of the box, and then put it on another machine without those libraries, then I get an error on program startup:

> The program can't start because `libstddc++-6.dll` is missing from your computer.

Right after there is a similar error, but for `libgcc_s_dw2-1.dll`
Adding `-static-libgcc` and `-static-libstdc++` to the library path builds those libraries into the executable, removing the occurrence of the errors, and so the application can be shipped to other Windows machines.

I guess it's only IVAN specific, and then only peculiar to Windows, so goes in the `CMakeLists.txt`?

**Comment by emlai** [comment]
Ok I see. I'll add them to `CMakeLists.txt`.
