### ISSUE TITLE
Convert graphics files from PCX to PNG

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#189]
GitHub allows diffing of PNG images, but not PCX, so this would make it easier to see what exactly has changed when the image files are modified. See related discussion in #143.

**Comment by fejoa** [comment]
Does git "merge" .pcx files like it would a normal binary file?

**Comment by emlai** [comment]
@fejoa yes

**Comment by fejoa** [comment]
I'm just wondering how the kamikaze dwarf problem managed to resurface again all those months ago. Maybe I or someone else merged in a slightly older graphics file at some point and the old kamikaze dwarf leg pictures made it back in?

**Comment by emlai** [comment]
Well, if we look at the [commit history of `Humanoid.pcx`](https://github.com/Attnam/ivan/commits/master/Graphics/Humanoid.pcx) we see that commit 03de372f435a2fb0cb39e4d732f10e1d2e1a5ea7 added a bunch of new graphics including the dwarf leg offset, then commit bf2fbdd60c779ef0e7fe29dceed0b1fec3fee2dc reverts most of those changes (including the dwarf leg offset).
