### ISSUE TITLE
Holy hand grenade automatically triggers upon entry to a new level

### ISSUE THREAD

**Issue by rvanherel** [Attnam/ivan#19]
Actually, the holy hand grenade automatically triggers when wished as well...

**Comment by Clawzfire** [comment]
Did some testing, and it looks like this bug is introduced in 21bad755b338dad2f7f92b2d0d93214004603a05, though I'm not sure where.

**Comment by rvanherel** [comment]
The bug arises from this line in materia.h
https://github.com/Attnam/ivan/commit/21bad755b338dad2f7f92b2d0d93214004603a05#diff-05ad7f5dfecedcf40bd8fca98bf176b7R27

If I set virtual truth HasBe() const { return false; } then the problem goes away. So there is something about the way an *item* inherits a Be() from a solid *material* with a Be().
If the theory is correct, then in CVS, a holy hand grenade made from banana peel should instantly explode.

I think if I add a check in holyhandgrenade::Be() for a non-zero PinPulledTick then the problem with the hand grenade should go away, but alas, that does not preclude further bugs from appearing.

**Comment by rvanherel** [comment]
This is fixed by: https://github.com/Attnam/ivan/commit/bc19173f254914e89a80b3d025c4cda5ff78f7f0
