### ISSUE TITLE
Could not start on Windows 10!

### ISSUE THREAD

**Issue by filpas** [Attnam/ivan#230]
I tried to start IVAN v0508 on Windows 10 64 bit.

Error shows

The program can't start because libgcc_s_dw2-1.dll is missing from your computer. Try reinstalling the program to fix this problem.

The program can't start because libstdc++-6.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by fejoa** [comment]
You might have the "early release" bug. Try downloading the new zip file and installing that copy.

**Comment by filpas** [comment]
That solved the problem. Thanks.
