### ISSUE TITLE
Burning monsters and items should be visible with Infravision

### ISSUE THREAD

**Issue by Azba** [Attnam/ivan#24]
Being heatvision and all. For monsters you could just toggle the IS_WARM BodyFlag alongside burning status, but I'm not sure how you'd go about it for items. Or even whether to bother with items since as far as I know there's no way for ESP or Infravision to pick up anything but monsters currently. You'd probably have to butcher up the detect material code.

**Comment by andrewtweber** [comment]
ESP does not detect lamps or other item heat sources so I think this should only be for burning monsters.

**Comment by rvanherel** [comment]
Can you infravision through walls?
It gives me an idea for a Psi vision, where you can detect monsters according to their panic level. A burning monster will be panicked and likely give off levels of psychic distress.

**Comment by Azba** [comment]
Both ESP and Infravision see through walls. 
I dunno about "Psi vision" say, since that basically sounds like ESP (maybe you can detect panicked enemies from further away for your example?) but maybe for the case of panicked monsters or such you could add a brand new effect based on *smell* that's similar to ESP except you can pick up monsters with sweat on them (panicked!) or ones that are otherwise smelly (rot, orcs in general).

Probably too much effort though.
