### ISSUE TITLE
Missing error checks for fread

### ISSUE THREAD

**Issue by marmistrz** [Attnam/ivan#242]
```
In file included from /home/marcin/.cache/pacaur/ivan/src/ivan/Main/Include/bodypart.h:17:0,
                 from /home/marcin/.cache/pacaur/ivan/src/ivan/Main/Include/char.h:16,
                 from /home/marcin/.cache/pacaur/ivan/src/ivan/Main/Source/dataset.cpp:13:
/home/marcin/.cache/pacaur/ivan/src/ivan/FeLib/Include/save.h: In member function ‘void inputfile::Read(char*, long int)’:
/home/marcin/.cache/pacaur/ivan/src/ivan/FeLib/Include/save.h:75:70: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   void Read(char* Offset, long Size) { fread(Offset, 1, Size, Buffer); }
```
Since it's C++, you may want to use `fstream`. 
If you assume no error should appear, it's better to crash the whole thing to hell than to experience strange bugs.

**Comment by emlai** [comment]
Nice catch. My libc doesn't declare `fread` with that attribute :(

There's an ancient comment a couple of lines above:

>     /* fstream seems to bug with DJGPP, so we use FILE* here */

The bug has probably been fixed ages ago, and even if not, we don't actively support DJGPP anymore, so I'm fine with switching to `fstream`. 👍
