### ISSUE TITLE
global-hall-of-fame - problems linking libcurl on Windows

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#257]
Using [MSYS2](http://www.msys2.org/), I am able to download and install the toolchain and compile IVAN with no complaints. 

In `msys2.exe`, I used the following commands to install the rest of SDK to compile for `WIN32`:

`$ pacman -S git`
`$ pacman -S mingw-w64-i686-gcc`
`$ pacman -S make`
`$ pacman -S mingw-w64-i686-cmake`
`$ pacman -S mingw-w64-i686-libpng`
`$ pacman -S mingw-w64-i686-SDL2`
`$ pacman -S mingw-w64-i686-pkg-config`

`libcurl` and the rest seem to get installed along the way somewhere. It's easy to check that it is installed.

Then:
`$ git clone https://github.com/emlai/ivan.git` and switch to `global-hall-of-fame` etc

Open MinGW32.exe in the msys2 directory
`$ cd C:/emlai`
`$ mkdir MSYS2`
`$ cd MSYS2`
`$ cmake .. -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=C:/emlai/inst_msys2`
`$ make -j4 install` etc

It's only when I run the executable, I get a procedure entry point error along the lines of:

`
The procedure entry point SSL_COMP_free_compression_methods could not be located in the dynamic link library
C:\msys64\mingw32\bin\libcurl-4.dll.
`

Can't fathom what the missing step might be. Either need some more CMake machinery, or the `libcurl` is not configured correctly. It'd be nice to get this going because MSYS2 is actively maintained and would make it easier to build on `WIN32`. Hoping for some brave fellas to help fight the Ballmernator!

**Comment by fejoa** [comment]
It runs if I type `./ivan` in the `MinGW32.exe` command window. And it submits high scores!
Just need to find out how to run the `ivan.exe` without the need for the command line.

**Comment by fejoa** [comment]
`MSYS2` install works fine now. I will put some instructions up at some point.
Next up is `MinGW32-make` to build ivan.exe

@emlai any idea if `libcurl` needs any extra linkage flags under windows?

**Comment by emlai** [comment]
> @emlai any idea if `libcurl` needs any extra linkage flags under windows?

No idea :(

**Comment by fejoa** [comment]
closed by #259
