### ISSUE TITLE
Armed Holy Handgrenades not separated in inventory.

### ISSUE THREAD

**Issue by Clawzfire** [Attnam/ivan#26]
If you have a stack of holy handgrenades, then pull the pin off of the top one, you are left unable to arm the others until you drop/throw the first.

Armed grenades should be kept in an item stack separate from those that still have their pins in place.

**Comment by rvanherel** [comment]
fixed by this https://github.com/Attnam/ivan/pull/28

**Comment by rvanherel** [comment]
by "fixed" I meant "slightly improved"

**Comment by rvanherel** [comment]
Fixed: https://github.com/Attnam/ivan/commit/65a0e8efcc6d89e52309625b3f410dcda8fb1298
