### ISSUE TITLE
Balance amulet of elemental protection

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#268]
Amulet of elemental protection is OP, needs to be tuned back

**Comment by red-kangaroo** [comment]
Toned down [here](https://github.com/Attnam/ivan/pull/272/commits/df8504f5b515fb5cbf8483c0aea193d3cc0e024e), gives only as much resistances as corresponding rings. Thus still more pwoerful than rings, but uses an amulet slot.

**Comment by fejoa** [comment]
Sweet, great work. Will be sure to close this issue once you PR is merged :)

**Comment by andrewtweber** [comment]
This can be closed right?
