### ISSUE TITLE
Direction keys appear to press twice

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#283]
For certain actions (so far I've discovered it with chatting and applying a stethoscope), after you press the direction key, it appears to take the input twice.

So for example when I tried to apply a stethoscope to myself using `numpad 5` it would flash the "information about you" and then immediately close it. (If I used the `.` key instead it worked)

When I tried to chat with the blacksmith in Attnam, I had to specify direction because another NPC was next to me. After I specified the direction, the blacksmith asked what I wanted to have repaired but that dialog immediately closed before I could choose an item.

**Comment by fejoa** [comment]
Arrgh! That's related to the numpad fix. Probably needs a check for whether ```'g'o``` is active

**Comment by andrewtweber** [comment]
@fejoa I actually don't think it's directly related. I tried reverting your change to `Main/Source/char.cpp`

https://github.com/Attnam/ivan/pull/276/files#diff-4cadc0208ffad4bddcb5b649814f7d9b

So that `go` and `dig` are broken again. But applying a stethoscope to myself still detects the `numpad 5` key twice.

**Comment by andrewtweber** [comment]
Fun update: this only affects Mac (/Linux) not Windows

**Comment by andrewtweber** [comment]
It's working!
