### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LargeBee** [Attnam/ivan#293]
I downloaded ivan 0.50.9 a week after it came out and had this problem and I came back now to see if anyone else is having this problem, and well, here I am

I am running Windows 10 and whenever I launch the game the screen is white, it never reaches the main menu, and then a windows box comes up saying ivan.exe has stopped working.

ivan 0.50.8 works absolutely fine so I'm not quite sure what's going on here
btw, I simply downloaded the zip file I didn't compile from source or anything

Below I have included screenshots of ivan 0.50.8 running and a screenshot of ivan 0.50.9 well, uh, not running

![j5tkvqt](https://user-images.githubusercontent.com/22668293/32994830-53704374-cd64-11e7-8202-220986460bbb.png)
![1keic2x](https://user-images.githubusercontent.com/22668293/32994836-56527c9c-cd64-11e7-8502-a91f98b6e132.png)

**Comment by andrewtweber** [comment]
@LargeBee  is 0.51 working, is that why you closed it?
