### ISSUE TITLE
fountain bug

### ISSUE THREAD

**Issue by badbeaver** [Attnam/ivan#303]
drank from a fountain and it threw me into a wall
![ivan_2017-12-19_22-39-50](https://user-images.githubusercontent.com/34551546/34175571-edd60dd4-e50d-11e7-89bb-80323479f3a0.png)

**Comment by badbeaver** [comment]
sorry  i am stupid
![ivan_2017-12-19_22-44-42](https://user-images.githubusercontent.com/34551546/34175643-384abc8e-e50e-11e7-8fe2-8378802857f3.png)

**Comment by andrewtweber** [comment]
Ha, what are the odds! Serious question.. I wonder if the fountains were intended to reveal secret rooms to you and have a higher chance of placing you in one?

**Comment by badbeaver** [comment]
That would be a great way to teach new players that there are secret rooms, but I don't think that is the case because there are not a lot of them and they are for the most part pretty obvious. And by the way, is there is less secret rooms in GC after the new update? Because I can't find any.

**Comment by andrewtweber** [comment]
GC layout shouldn't be affected by any of the releases
