### ISSUE TITLE
Crash on UT3

### ISSUE THREAD

**Issue by badbeaver** [Attnam/ivan#307]
So I drank out of a fountain at UT1 and it looks like it teleported me on UT3, then IVAN immediately crashed.
![ivan_2017-12-23_14-30-03](https://user-images.githubusercontent.com/34551546/34319254-48524678-e7ee-11e7-900c-402e49a78351.png)

**Comment by fejoa** [comment]
Did you by any chance drop your old bones files into the new IvanWin051 directory?

**Comment by andrewtweber** [comment]
Yes if you switched versions (i.e. updated data files) and try to load an old game or an old bones file it will crash.

**Comment by badbeaver** [comment]
yes sorry

**Comment by emlai** [comment]
Could we add the version number to bone files so that the game can check it before trying to load the file, to avoid crashes like this? I think this has happened to me a few times and it would be nice to fix this.
