### ISSUE TITLE
Fully applied Ivan3D patch on the latest

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#316]
Here is the mergeable branch:
https://github.com/AquariusPower/ivan/tree/ApplyIvan3Dpatch
(EDIT: I just improved it by updating the outlined graphics with the new additions from latest development here, see the comparison of the graphics side by side here: https://github.com/Attnam/ivan/compare/master...AquariusPower:ApplyIvan3Dpatch)

There are still a few problems (on linux at least):
- Too slow when drawing hidden things in iso mode (that remain hidden), not sure yet how to fix this one.
- EDIT: FIXED (by adding the .dat changes from Ivan3D-11) - some terrain blocks are missing wall and/or ceiling, but I think it is easy, by just adding the correct configuration on the .dat files

Can someone test it on windows?

**Comment by red-kangaroo** [comment]
Is this toggleable?

**Comment by AquariusPower** [comment]
@red-kangaroo 
It actually starts with all 3D features disabled, like vanilla.
You can just press 'x' and it will also toggle between 3d and vanilla, or use the config menu.
You can try the original using wine to run it on linux if you are not on windows (btw the 3D can be 1st person or isometric).
The isometric is good because the graphics become like double size (not more detail, just bigger to be seen), and is easier on my eyes :)

**Comment by AquariusPower** [comment]
It seems that Ivan3D is the implementation of a specific 3D engine for Ivan.
igraph.cpp -> tileWalls() -> tileRect() -> fDrawRect() -> DOUBLE_BUFFER->PutPixel() 
makes it quite clear.

Only someone who really understands how to maintain a 3D engine could maintain Ivan3D code. I dont know how to do that :(
