### ISSUE TITLE
Non conflicting Eclipse project files and preferences for all developers.

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#328]
my .gitignore added text:
```
######
## Eclipse developers preferences over different operational systems
## and personalized configurations.
######

# link to some user folder at /.devsPrefs
/.devsPrefs/Current

# direct links to preferences at /.devsPrefs/Current
/.cproject
/.project
/.settings

# Git ignore files are special. They are relative to their current path!
# If the one at '/.devsPrefs/SomeUserName/.gitignore' remains named like that,
# git will recognize and ignore files as that sub folder is a root folder!
# Therefore ONLY that file must be named like: '/.devsPrefs/SomeUserName/.gitignore.SomeUserName'
# And after creating the link to it, the link itself must be renamed to '.gitignore' to be again recognized by git.
/.gitignore
```

Here are the symlinks each user can easily create thru drag-n-drop like in Nautilus (on linux). EDIT: I also added a linux script to automate that based on the "Current" symlink target:
```
.cproject -> .devsPrefs/Current/.cproject
.gitignore -> .devsPrefs/Current/.gitignore.AquariusPower 
.project -> .devsPrefs/Current/.project
.devsPrefs/Current -> AquariusPower     # this link is to the current user selected preferences folder
```

real directories with custom preferences
```
.devsPrefs/AquariusPower
.devsPrefs/Attnam
```

here the branch: https://github.com/AquariusPower/ivan/tree/DevelopersPreferences

If you agree, test and it works, and it doesnt seem overly/unnecessarily complicated, I will create the pull request :). 
I read we shouldnt commit project files in vcs, but.. it is actually possible this way! 
Created this [gist doc](https://gist.github.com/AquariusPower/ef4e9f8e9d9a9359feeb07dc95cb804f) too.

**Comment by AquariusPower** [comment]
I am still having trouble with .gitignore, Iwill close this for now ...

**Comment by fejoa** [comment]
I don't use eclipse (insane, yes), so feel free to make a PR for this

**Comment by AquariusPower** [comment]
cool ok.

Btw, I've been trying to improve/fix the current eclipse/linux config, and made it work much better.

I dont really need eclipse building it as CMake works great.

But it would be good tho if I could debug it, despite the debug logs work nice too (`grep`ping them for clues), I ended up adding a lot of debug code (that can be easily removed with `sed`)  and would probably not be necessary if I could just debug it like I do in java hehe.
In the other hand... if it is compiled using with the debug logs enabled, sending us such log + the crash stack would be very helpful I guess, so keeping the debug log code there may be useful one day.

The best thing on eclipse for me is the auto completion, and code navigation. Despite a bit slow here, work great most of the times, just dont use the "renaming variable feature" or you may lose all your latest changes... yes, a terrible oxygen eclipse bug.

**Comment by AquariusPower** [comment]
https://github.com/Attnam/ivan/pull/356
