### ISSUE TITLE
SDL2/SDL_stdinc.h not found

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#343]
After the xbrzscale was merged in, I'm not able to build on OSX anymore. I have SDL2 installed (through brew, also tried building source, and installing the SDL2.framework into /Library/Frameworks) but I keep getting this error:

```
In file included from/ivan/FeLib/Source/bitmap.cpp:24:
ivan/FeLib/../xbrzscale/libxbrzscale.h:20:10: fatal error: 'SDL2/SDL_stdinc.h' file not found
#include <SDL2/SDL_stdinc.h>
```

I'm sure it's just an include path that needs updating, but I don't know much about cmake or makefiles..

**Comment by andrewtweber** [comment]
Looks like `XBRZLIB_RELATIVEPATHSDL` needs to be defined. If it uses the relative headers `"SDL_stdinc.h"` instead of `<SDL2/SDL_stdinc.h>` it compiles the xbrz files successfully

However even with that I'm getting a failure without any details at the end:

```
15 warnings generated.
15 warnings generated.
42 warnings generated.
50 warnings generated.
150 warnings generated.
35 warnings generated.
26 warnings generated.
make[1]: *** [Main/CMakeFiles/ivan.dir/all] Error 2
make: *** [all] Error 2
```

Here is the full output... it's pretty massive. I definitely never got this many notes/warnings before.

https://gist.github.com/andrewtweber/43199e6901b9a4e77dc0a3bdbf1a90ff

**Comment by AquariusPower** [comment]
how it compares to the Linux and WIN32 logs about warnings count? but the goal is detect what causes the Error 2 anyway..

travisci OSX compilation worked, but I have no other ideas about it (never used OSX), anyway could the config for it be compared with the one you are using?

**Comment by AquariusPower** [comment]
I found this on the log:
```
/Users/andrew/ivan/Main/Source/message.cpp:17:10: fatal error: 'pcre.h' file not found
#include <pcre.h>
         ^~~~~~~~
1 error generated.
make[2]: *** [Main/CMakeFiles/ivan.dir/Source/message.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

```
better fix it first!

**Comment by andrewtweber** [comment]
Ah thanks for catching that. And just to be clear I am definitely not blaming you for the build issues :) I just want to make sure that it can build cleanly in any environment since we added new libraries. I'm excited to test the graphic scaling!

**Comment by AquariusPower** [comment]
cool xD, np!
I think I read many of those warnings before, and they were there b4 I touched it, all (or most?) related to stuff I didnt change, that's why I asked you to compare, mainly if possible with a build previously to the xbrz patch, to make it sure what part is really related to xbrz, but warnings are not errors anyway.

And there are a few persistent warnings that are hard to "fix" like the printf format:
```
feio.cpp:70:50: warning: format not a string literal and no format arguments [-Wformat-security]
       FONT->Printf(&Buffer, PrintPos, Color, Line);

```
I looked at the code but promptly gave up as not required to let it work, and probably hard to workaround w/o messing the code unnecessarily I guess. (I still have no idea, as havent spent more than 1 minute on it :))

Anyway, the best thing as always it to provide the full log, that's what really matters :)

**Comment by fejoa** [comment]
@andrewtweber does it build now?

**Comment by andrewtweber** [comment]
I have pcre installed (actually it was installed already), it just doesn't know where to look for the header files apparently.

**Comment by AquariusPower** [comment]
mmm... interesting, I read OSX is essentially like linux right?
try this in the command prompt:
`locate pcre.h`

**Comment by fejoa** [comment]
Do we need to add something to the cmakelists to search for the library, for example: https://github.com/LuaDist/pcre/blob/master/FindPCRE.cmake ?
We already have an SDL2 search in our cmakelists: https://github.com/Attnam/ivan/blob/master/FeLib/FindSDL2.cmake

**Comment by AquariusPower** [comment]
@fejoa 

I was reading the cmake and there is some instructions for OS X, unfortunately I  get quite lost reading it because I never used OS X...

If the files were at the same place where the linux ones are!? we need someone that knows how to configure it at OS X, do you know who created the cmake files? mainly the OS X instructions? that would be great!

**Comment by fejoa** [comment]
> do you know who created the cmake files?
That would be @emlai

**Comment by andrewtweber** [comment]
`locate pcre.h` yields:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/ext/pcre/php_pcre.h
/usr/local/Cellar/pcre/8.39/include/pcre.h
/usr/local/Cellar/pcre/8.39/share/doc/pcre/html/pcre.html
/usr/local/Cellar/pcre/8.41/include/pcre.h
/usr/local/Cellar/pcre/8.41/share/doc/pcre/html/pcre.html
/usr/local/Cellar/pcre/8.42/include/pcre.h
/usr/local/Cellar/pcre/8.42/share/doc/pcre/html/pcre.html
/usr/local/Cellar/php@7.1/7.1.16_1/include/php/ext/pcre/pcrelib/pcre.h
/usr/local/Cellar/php@7.1/7.1.16_1/include/php/ext/pcre/php_pcre.h
/usr/local/include/pcre.h
```

**Comment by AquariusPower** [comment]
I think I know what the problem can be, despite shouldn't:
"/usr/**local**/include/" may not be being looked for as it is kind of optional I guess, it should but clearly is not.
"/usr/include/" is where it finds mine!

now we need the solution :)

**Comment by AquariusPower** [comment]
I was reading `./FeLib/FindSDL2.cmake`, and I am positively sure that tweaking a copy of it will make pcre work on OSX.

There are parts/tests of it that must be removed/unnecessary.

But it has the basics:

SET(SDL2_SEARCH_PATHS
	~/Library/Frameworks
	/Library/Frameworks
	**/usr/local**
	/usr
	/sw # Fink
	/opt/local # DarwinPorts
	/opt/csw # Blastwave
	/opt
)

as I understand we just need the .h and the library (.so here), if the lib is named equally on OSX this may help on finding it:
`find / -iname "libpcre.so*" 2>/dev/null`

but I guess you may look directly on similar paths to these:
/lib/i386-linux-gnu/libpcre.so.3
/lib/i386-linux-gnu/libpcre.so.3.13.2
/lib/x86_64-linux-gnu/libpcre.so.3
/lib/x86_64-linux-gnu/libpcre.so.3.13.2
/usr/lib/x86_64-linux-gnu/libpcre.so
(despite it will most probably be under /usr/local)

**Comment by AquariusPower** [comment]
ugh lol,

fejoa's tip is much better and simpler:
https://github.com/LuaDist/pcre/blob/master/FindPCRE.cmake

I think we can mix both.

**Comment by AquariusPower** [comment]
I am having a hard time trying to understand cmake code, so far:

```
# we need to let these paths be looked for
SET(PCRE_SEARCH_PATHS
	~/Library/Frameworks
	/Library/Frameworks
	/usr/local
	/usr
	/sw # Fink
	/opt/local # DarwinPorts
	/opt/csw # Blastwave
	/opt
)

# find there
FIND_PATH(PCRE_INCLUDE_DIR pcre.h PATHS ${SDL2_SEARCH_PATHS})
FIND_LIBRARY(PCRE_LIBRARY pcre PATHS ${SDL2_SEARCH_PATHS})

# finally set
SET(PCRE_LIBRARIES ${PCRE_LIBRARY})
SET(PCRE_INCLUDE_DIRS ${PCRE_INCLUDE_DIR})

# and use then in ANOTHER CMAKE FILE like at Main/CMakeLists.txt
file(GLOB IVAN_SOURCES Include/*.h Source/*.cpp ${PCRE_INCLUDE_DIRS})
target_link_libraries(ivan FeLib FeAudio SDL2_mixer ${PCRE_LIBRARIES} xbrzscale)
```

the problem is that I dont have an environment to test it..

**Comment by iology** [comment]
You can try my branch here: https://github.com/jakwings/ivan/tree/issue-343 (unready for a pull request)

Then use these commands to build:

```bash
mkdir -p build && cd build

env PKG_CONFIG_PATH="$IVAN/zlib/lib/pkgconfig:$IVAN/libpng/lib/pkgconfig:$IVAN/pcre/lib/pkgconfig" \
    SDL2DIR="$IVAN" \
    cmake .. -DCMAKE_INSTALL_PREFIX="$IVAN/ivan"

make
make install
```

Just replace `$IVAN` with `/usr/local` if you're using homebrew.

**Comment by AquariusPower** [comment]
@andrewtweber btw, I just thought that, if you could re-install pcre as a system wide lib, that would most probably solve the issue. If there is no pcre package to your system, may be using some automation tool like `checkinstall` (I use for .deb packages), could do the trick as it let you install in system wide folders and keep track of the install actions letting them be undone when upgrading or uninstalling the customized new package.

**Comment by iology** [comment]
Just fixed my script above. :P

@AquariusPower Personally I use the SDL2 frameworks downloaded from the offical website. They can be easily bundled without any modification. Only libpng and libpcre need to be compiled and linked (statically or dynamically). It is easy to manually set the search paths for the dynamic libraries with `/usr/bin/install_name_tool`. Travis CI is definitely useful for this, like what I did: https://github.com/auto-load/Cataclysm-DDA/blob/osx-build/.travis.yml

**Comment by andrewtweber** [comment]
I'm not sure who fixed it, seems like a combined effort, but thank you all :) It is building now!

**Comment by AquariusPower** [comment]
@iology did [all the hard work](https://github.com/Attnam/ivan/pull/388) (or most probably all the work), I just hack&slashed providing clues but the bamboo golem hit my lantern that exploded, burned by scroll of wishing and I had to flee running in the dark while touching the cold walls of the underwater tunnels... or something like that :>

**Comment by SYUMJOBA** [comment]
I got this error while trying to include SDL_mixer.h (trying to work with audio)

I open up the thing and I see
`#include "SDL_stdinc.h"`

### And I'm like 
>"Am I joke to you? Spent all this time setting up include headers and now you want them relative?

I very **_violently_** but very **_effortlessly_** edited all the `#include`s to look for `<SDL/header_name>` and now it works :)
