### ISSUE TITLE
new "Auto play" for wizard mode.

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#350]
I added a autoplay feature, that uses existing NPC AI.
It is only available thru wizard mode.
To enable/disable it you need to press '~' key.

Every time we rest '.' it will not and will do some action like fight, eat, move etc...

I am trying to let it play by itself every 2 seconds or faster, so we can let it playing and do other things, waiting for crashes to fix.

What I need to know is if it is better to create another new pull request or I should put it at one of the other PRs I already created?

**Comment by fejoa** [comment]
I think this is a new subsystem, so it really should get its own pull request

**Comment by AquariusPower** [comment]
done
