### ISSUE TITLE
Provide an option to always use nearest-neighbor scaling for upscaling?

### ISSUE THREAD

**Issue by iology** [Attnam/ivan#357]
From the source code we can see that nearest-neighbor scaling is always preferred when possible:

https://github.com/Attnam/ivan/blob/3d1271d234e8ebdc796289e94ca1ff8b36849271/FeLib/Source/graphics.cpp#L223-L250

Without an extra large (external) HD display, linear scaling currently only makes more sense for downscaling, for upscaling it blurs the picture **especially for the text using a bitmap font**. There are no higher-resolution image/font assets for downsampling. e.g. 2x for around(800x600) < size < around(1600x1200)

I can't stand the blurred text on my retina-mabook, so I always disable linear scaling. The pixelated text hurts much less than the blurred text does for my eyes.

**Comment by AquariusPower** [comment]
may be the font can be upscaled 2x, 3x.. 6x using xBRZ, that file saved and used as alternative, so no need to draw manually, but I am not sure if the result will be usable as a font, some tests are required (if I clearly understood the problem)

**Comment by iology** [comment]
The font issue is indeed foremost to me. But the images are also scaled, so even the 1x dungeon looks different when using different scaling algorithms, however the blurring is less obvious with 3x-6x dungeon. I use 3x dungeon. My situation is (not in full screen mode):

* `VirtualDisplayMode` (virtual screen size of the OS): 1280x800 (actual: 2560x1600), device-pixel ratio=2
* `NewRes` (virtual screen size of the game): 800x600
* `ActualWindowRes` (drawable canvas size for the game): 1600x1200
* `ActualDisplayRes`: 2560x1600 (not considering the top bar of MacOS and title bar of the game window ;-)

I feel the logic in the code is wrong, will delve into it later. According to the result, the picture is scaled. 2x, 4x, 6x, 8x, 10x, 12x needed for downsampling to 1x-6x dungeons and text (because the pixel ratio is 2.0, not 1.5, 3.0, ...)

Anyways, I like pixel art and my eyesight can bear with the dense but still legible pixelated text (in nearest-neighbor scaling mode). My patch is simple: just `SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "nearest")`. :P

<details>

<summary>Some screenshots (if you have a rMBP to check them):</summary>

1x dungeon (linear):
<img width="800" alt="ivan-1x-dungeon-linear" src="https://user-images.githubusercontent.com/23622455/40358295-4fc582de-5df1-11e8-9505-3e614f41f66c.png">

1x dungeon (nearest):
<img width="800" alt="ivan-1x-dungeon-nearest" src="https://user-images.githubusercontent.com/23622455/40358296-5069e964-5df1-11e8-83ad-0e06127d64b8.png">

3x dungeon (linear):
<img width="800" alt="ivan-3x-dungeon-linear" src="https://user-images.githubusercontent.com/23622455/40358298-50b6a10a-5df1-11e8-9793-f22e4b430378.png">

3x dungeon (nearest):
<img width="800" alt="ivan-3x-dungeon-nearest" src="https://user-images.githubusercontent.com/23622455/40358299-50edfc9a-5df1-11e8-95af-cca5f471002e.png">

6x dungeon (linear):
<img width="800" alt="ivan-6x-dungeon-linear" src="https://user-images.githubusercontent.com/23622455/40358300-512a7e54-5df1-11e8-90ff-e53d280311d8.png">

6x dungeon (nearest):
<img width="800" alt="ivan-6x-dungeon-nearest" src="https://user-images.githubusercontent.com/23622455/40358302-51628ed4-5df1-11e8-900b-c8500974ecad.png">

</details>

**Comment by fejoa** [comment]
Yep, nearest neighbour looks pretty nice

**Comment by iology** [comment]
https://github.com/Attnam/ivan/blob/bbae94d17888d0fbca13da5e9551b46be0a7e5d3/FeLib/Source/graphics.cpp#L239-L247

This logic is for full screen mode only, but it also affects window mode. However, due to the preference of nearest-neighbor scaling and lack of HD assets, better stick to pixel art for now. Patch: replace L223-250 with `SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "nearest");`

**Comment by AquariusPower** [comment]
@iology 
there is quite a lot of logic there, I didnt completely understand it yet:
```
  /* The following code will determine whether to use nearest neighbor or
   * linear interpolation when scaling the game in fullscreen mode. */

  SDL_DisplayMode VirtualDisplayMode;
  if(SDL_GetDesktopDisplayMode(0, &VirtualDisplayMode) == 0)
  {
    v2 ActualWindowRes; // On high-DPI displays this is greater than NewRes.
    SDL_GL_GetDrawableSize(Window, &ActualWindowRes.X, &ActualWindowRes.Y);

    v2 ActualDisplayRes;
    if(SDL_GetWindowFlags(Window) & SDL_WINDOW_FULLSCREEN_DESKTOP)
      ActualDisplayRes = ActualWindowRes;
    else
      ActualDisplayRes = v2(ActualWindowRes.X / NewRes.X * VirtualDisplayMode.w,
                            ActualWindowRes.Y / NewRes.Y * VirtualDisplayMode.h);

    if((ActualDisplayRes.Y % NewRes.Y == 0
       && ActualDisplayRes.X >= ActualDisplayRes.Y / NewRes.Y * NewRes.X)
       || (ActualDisplayRes.X % NewRes.X == 0
       && ActualDisplayRes.Y >= ActualDisplayRes.X / NewRes.X * NewRes.Y))
      /* In-game pixels can be safely mapped one-on-one to rectangular
       * units consisting of one or more on-screen pixels. */
      SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "nearest");
    else
      SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "linear");
  }
  else
    SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "linear");
```

It seems, someone did a great effort to prevent "nearest" from being used everywhere.
I think, intead of replacing that code, it could be an user option, at "graphics" section, like "force SDL nearest mode", and would end like this:
```
if(ivanconfig::IsNearestRenderMode()){
  SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "nearest");
}else{
 //the old code
}
```

**Comment by iology** [comment]
> It seems, someone did a great effort to prevent "nearest" from being used everywhere.

It seems not. It requests for "nearest" if the actual width/height of the display is a multiple of the virtual width/height of the game. BTW let's call out the committer @emlai for that part.

The code doesn't check fullscreen mode at L227 but at L233, so unlike what the code comment says, it also affects window mode. L236-237 calculates the actual display resolution from the actual window size.

https://github.com/Attnam/ivan/blob/bbae94d17888d0fbca13da5e9551b46be0a7e5d3/FeLib/Source/graphics.cpp#L226-L237

Q1: Has everyone got used to linear scaling? By default, "nearest" is used for SDL2 but IVAN's high-dpi related code changed it: https://wiki.libsdl.org/SDL_HINT_RENDER_SCALE_QUALITY

Q2: Is it now always needed for xBRZ scaling effect? (the xBRZ things came 3 years after the commit)

A new option for scaling mode seems good, but I think the old code looks weird and should also be fixed if this isn't too late. The player only needs to choose between "nearest" and "linear", maybe xBRZ can be included.

> check iconf.h and iconf.cpp here, is really simple :)

Thanks! I have added a simple yes/no option for this.

**Comment by AquariusPower** [comment]
>Q2: Is it now always needed for xBRZ scaling effect? (the xBRZ things came 3 years after the commit)
>A new option for scaling mode seems good, but I think the old code looks weird and should also be fixed if this isn't too late. The player only needs to choose between "nearest" and "linear", maybe xBRZ can be included but it requires a restart unless all textures are dynamically recreated.

initially (still without xBRZ regions scaling https://github.com/Attnam/ivan/pull/331#issuecomment-390428166),
I used the full screen scaling option, and it was blurry, one of the reasons I went thru xBRZ coding, therefore xBRZ is independent.

>Q1: Has everyone got used to linear scaling? By default, "nearest" is used for SDL2 but IVAN's high-dpi related code changed it: https://wiki.libsdl.org/SDL_HINT_RENDER_SCALE_QUALITY

I thought "nearest" was tried to be prevented because of performance drop and/or glitches,
but time passed and may be these are not a problem anymore.

The main point on letting user decide for the override, is if we arent aware of what the initial developer experienced as problems in the game, and these happen again in someone's else machine.

But if others agree that it is broken, a full code replacement would be the correct thing to do (like the savegame list that crashed/aborted when trying to load an old version of the savegame).

So indeed, letting user choose just between "linear" or "nearest" would be the best option (insted of "nearest" and the old code behavior).

**Comment by AquariusPower** [comment]
@iology 
btw, this https://github.com/Attnam/ivan/issues/324 have some talks about 64x64 graphics, the (huge?) effort required to let it happen one day :)

**Comment by fejoa** [comment]
>I am reading the docs inside the Doc/ folder. 😉 Is there an update for Doc/Work/Great Jobs.txt?

Heh. Try making sense of: https://attnam.com/wiki/Development_plans

Otherwise just go down the rabbit hole and look at the myriad suggestions down at the forum: https://attnam.com

**Comment by AquariusPower** [comment]
@iology 
most of xBRZ is not cached currently, it keeps drawing for the animations, and it's input is the final mixed complete result (the vanilla result, as per dungeon square 16x16 it will stretch directly from it).
Yes, there is a huge lot places for improvement, the point is if it is required, for now it is working sufficiently fast to continue being fun :)
May be let user decide "linear" or "nearest" is the best overall option so we dont impose anything.

here, I just used the xbrzscale application that is in this project (make compiling from the cpp file) with the font image file into 6x scale, if it helps :)
![font6x](https://user-images.githubusercontent.com/17087075/40654160-d40ee644-6313-11e8-8a31-f2c334efbdf0.png)
