### ISSUE TITLE
festring operator= sponginess

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#374]
EDIT: experimental branch https://github.com/AquariusPower/ivan/tree/FestringCopiesOnly

1st evidence in old save list code (what bug?)
```
      /* Buffer = ep->d_name; Doesn't work because of a festring bug */
      Buffer.Empty();
      Buffer << ep->d_name;

```

to test what happens after reading operator= code behavior:
```
PlayerName="test";
festring name = PlayerName;
name[0]='b';
// PlayerName becomes "best" ...
// even if you use this:
festring name = PlayerName.CStr();

```

expected behavior would be to copy the other festring `char*` value I guess...

a lot of places seem to use it in a non harmful way.

should we change it and check  every spot on the code using operator= ? may be.
should we extend std::string into a new festring? may be.
should we keep it as it is? may be :), learning curve and so on...

or did I miss something that makes the current operator= behavior be important?

now get a new developer, coding a huge lot of stuff, and 3 months later discover about it? scary...

EDIT:
may be one day: remove the 2 operator= 
to substitute it where essentially required create methods .AbsorbHook(char*) and .AbsorbHook(festring&)
what will break everywhere using operator= and be easy to change.
unless that's not a good idea :)

EDIT: and a new method something like: SetInternalDataAsCopyOf(char* or festring&)

**Comment by iology** [comment]
This is suspicious: https://github.com/Attnam/ivan/blob/b973bc99ab6a6a9bc3144fd29f67d286c0eb9caa/FeLib/Source/festring.cpp#L84

I guess that line should be `if((Data == StrPtr) && (OwnsData == Str.OwnsData))`?

**Comment by iology** [comment]
Line 72 and 80 are also problematic: https://github.com/Attnam/ivan/blob/b973bc99ab6a6a9bc3144fd29f67d286c0eb9caa/FeLib/Source/festring.cpp#L63-L91

The current `operator=` does not copy strings when the string data points to a `const char*` created at compile time, or when the string is already owned by another festring. It uses a reference counter to track if the data is being shared by others.

**Comment by iology** [comment]
To be really serious, we need to write a lot of tests for festring.cpp but I feel so tired. :P

**Comment by iology** [comment]
Or only refine those methods which can alter the festring, to make operator= "lazy" (copy-on-write). I haven't checked how frequent operator= is used.

**Comment by AquariusPower** [comment]
> write a lot of tests for festring.cpp

to precisely catch the bug would be good indeed

> I guess that line should be if((Data == StrPtr) && (OwnsData == Str.OwnsData))?

I actually think it means that if both results are not NULL, then do this complex non-documented thing to scare me at lest:
https://github.com/Attnam/ivan/blob/b973bc99ab6a6a9bc3144fd29f67d286c0eb9caa/FeLib/Source/festring.cpp#L86
that expands to
`++reinterpret_cast<ulong*>(StrPtr)[-1]`

but I didn't understand how that method works yet and why it does all those things about `Data` `OwnsData` `Reserved` ...

> Or only refine those methods which can alter the festring, to keep operator= "lazy" (copy-on-write)

operator= is always write self with parameter,
could you give me an example how it could be lazyfied? may be it is a good alternative I can't visualize yet :)

> Those two operator should be removed or redefined for mental health, and a new method RefAssign() be added.

if we just comment both operator= in .h and .cpp, it will easily break everywhere using it, making it quite easy to put an absorbing/RefAssign/hook/holdData/netherPortal or copying methods instead.

**Comment by AquariusPower** [comment]
ok, I checked on eclipse for the usages of both operator=, it is quite a lot of places.
I think, if we modify both operator= behavior to be just "copy the string overwriting internal data", the problem will be just:
- places where changing the assigned festring, when it gets modified, would also modify the absorbed other string, and that modification is expeced, intended and used like that, like:
```
fsB="nether";
festring fsA=fsB;
fsA<<" portal";
if(fsB!="nether portal")ABORT("");
```
the same if fsB was a simple `char*`.

**Comment by AquariusPower** [comment]
:ugh to my surprise, this compiled and run w/o crashing https://github.com/AquariusPower/ivan/tree/FestringCopiesOnly
the differences:
https://github.com/Attnam/ivan/compare/master...AquariusPower:FestringCopiesOnly

**Comment by iology** [comment]
Yeah, operator= avoids touching the memory allocator and deallocator as much as possible.

To understand what the `REFS` macro is doing, just look at `festring::CreateOwnData()`:

```
START |<- reference counter ->|<- reserved memory for chars ->|<- '\0' ->| END
                              ^
                              |
                              +-- Data

REFS(Data) := Data[-1] := Data - 1
```

What you're doing above is just discarding the referenced data and create a new copy, so it does work. The old behavior is to save memory ("lazy" for memory allocation) and avoid bothering the memory deallocator (for speed?). So we should also check if this behavior is used to modify the shared data for multiple festrings at the same time, even if it doesn't crash.

**Comment by iology** [comment]
I incline to make keep the current behavior for now and make other methods create an own copy before modifying the data, if there is no synching problem.

**Comment by AquariusPower** [comment]
sure, the worst scenario would be it corrupting the savegame data if sync is required.

> Note: also needs REF_MAX (<= ULONG_MAX) to ensure there is no overflow.

This means that a single session (if kept the current behavior that absorbs external data pointer) could lead to some weird thing happening, after we, for ex., let it auto-playing wizard w/o crashing for some days (what may generate a huge lot of festring interactions)?

**Comment by AquariusPower** [comment]
after some time I found an issue

`festring material::GetName(` at https://github.com/AquariusPower/ivan/blob/FestringCopiesOnly/Main/Source/materia.cpp#L49
It uses a static festring, and returns a local festring initialized by that static one.

The problem is, the local extremely short life at https://github.com/AquariusPower/ivan/blob/FestringCopiesOnly/Main/Source/bodypart.cpp#L3242
(that now uses `cfestring` instead of `cchar*`) was prone to bug at anytime someone add some code just after it , and I still have no idea why...

the bug, on keeping it as cchar* was that the log message "Acidous brown slime dissolves your left arm." would show like "Acidous x+#@* dissolves your left arm.", as `cchar* MName` was being corrupted.

**Comment by iology** [comment]
The really problematic method is `festring::CStr()`: it can produce `cchar*` from dynamically allocated data which may soon be deallocated later (when `REFS(Data) == 0`).

**Comment by AquariusPower** [comment]
I think the deallocation happens as soon the code change from one line to another.
So:
cchar* MName = fs.CStr(); //from this code instruction on it is out of control so next line may break it if makes any string allocation, was what I guessed, but I havent tested exactly what kind of code may break MName yet..
