### ISSUE TITLE
[windows] Fantasy names: Does it properly randomize?

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#400]
If I select the naming pattern "!sV !ss" I always get "Rilund Kinou" as the first option. Is the random number generator properly seeded?

**Comment by AquariusPower** [comment]
could you check the command line executable again? 
there and in the game it is getting well randomized on linux.
I think there may have another mingw workaround required to let it randomize properly.

**Comment by fejoa** [comment]
I used the cmd exec a couple of times and I got the usual list of first 5 names:

```Rilund Kinou
Perler Arai
Nysald Adie
Estet Umey
Nalack Rilia
```

So it would seem the RNG is not properly seeded under MinGW.

Possibly needs a MinGW thingee here: https://github.com/Attnam/ivan/pull/363/files#diff-b71de61b6082bd7ddc1b9cf4341d4d2eR23

BUT: FeMath should have a decent RNG in it somewhere? I wonder if this could be utilized?

**Comment by fejoa** [comment]
Hmm, more sleuthing seems to confirm our suspicions: https://stackoverflow.com/questions/18880654/why-do-i-get-the-same-sequence-for-every-run-with-stdrandom-device-with-mingw

How can we make the fantasy name generator rely on IVAN's native `RAND()` function?

**Comment by AquariusPower** [comment]
may be by exposing the `static std::random_device rd;` from namegen.cc so it can be changed

**Comment by fejoa** [comment]
> `rng` is used at `Random::toString()` there, we could just use `clock()` or ivan RAND() I guess

I'm having trouble hacking this. Do you have any tips on how to implement?

**Comment by andrewtweber** [comment]
Works on Unix
