### ISSUE TITLE
NPCs restore equipped items - should be non-configurable?

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#406]
"NPCs restore equipped items after polymorph" seems like an odd config option to me. The only other gameplay config affects the player and his pets. The player should not have control over other NPCs.

I think this should just always be set to "everyone" and not be configurable. Otherwise, it does have a tiny effect on the difficulty of the game.

**Comment by AquariusPower** [comment]
That was the reason I kept it as an option,
but also IMHO all NPCs should use that always as it clearly looks was a missing feature,

I just was not sure at the time if the vanilla gameplay should be changed,
but from many other merged pull requests that made the game more hardcore and cool,

**we should just do that.**

**Comment by fejoa** [comment]
This feature seems pretty bug free as well. I think we can make it non-configurable. I wonder if there are other options in the config menu we can consolidate in a similar way?

**Comment by AquariusPower** [comment]
btw, I think the defaults of many should be changed to provide the features you prefer the end users have from the beggining. All the ones I created kept the game working as in vanilla state.

Another option would be to have presets, and give them names like:
- full zoom and nice looking
- all new functionalities enabled at max (like the dynamic/immersive modes)

But these presets may be unnecessarily complicated to code and not fit well for most users in the end...

**Comment by AquariusPower** [comment]
we need decide the defaults https://github.com/Attnam/ivan/issues/410#issuecomment-397782109,
they are simple to change at iconf.cpp, feel free to set'em,

I'd like to share my cfg, 
my machine is a bit slow sometimes, and this config let the game works well.
but I play not in full screen (I like to keep a watch on the OS monitoring tools "system load indicator" on the tray), and I have FullHd widescreen and so the details are all towards it, like a pre-set :).

```
DefaultName = "";
FantasyNamePattern = "!ss !sV";
DefaultPetName = "Kenny";
AutoSaveInterval = 25;
AltAdentureInfo = 1;
BeNice = 1;
HoldPosMaxDist = 1;
MemorizeEquipmentMode = 2;
WarnAboutVeryDangerousMonsters = 1;
AutoDropLeftOvers = 1;
SmartOpenCloseApply = 1;
CenterOnPlayerAfterLook = 1;
ShowGodInfo = 1;
ShowMapAtDetectMaterial = 1;
GoOnStopMode = 3;
WaitNeutralsMoveAway = 1;
Contrast = 100;
WindowWidth = 1920;
WindowHeight = 1025;
GraphicsScale = 1;
FullScreenMode = 0;
ScalingQuality = 0;
LookZoom = 1;
XBRZScale = 1;
XBRZSquaresAroundPlayer = 3;
SilhouetteScale = 6;
AltSilhouette = 3;
AltSilhouettePreventColorGlitch = 2;
AltListItemPos = 2;
AltListItemWidth = 1000;
StackListPageLength = 80;
DungeonGfxScale = 5;
OutlinedGfx = 0;
FrameSkip = -1;
ShowItemsAtPlayerSquare = 10;
RotateTimesPerSquare = 5;
HitIndicator = 4;
ShowMap = 4;
PlaySounds = 1;
Volume = 37;
MIDIOutputDevice = 2;
DirectionKeyMap = 0;
SaveGameSortMode = 1;
ShowTurn = 1;
ShowFullDungeonName = 1;
SelectedBkgColor = "8,8,75";
AllowImportOldSavegame = 1;
SavegameSafely = 1;
HideWeirdHitAnimationsThatLookLikeMiss = 0;
GenerateDefinesValidator = 0;
```
(cant upload txt files?)

**Comment by iology** [comment]
I don't enable hit effect because it crashes the game very often and I don't know how to fix the gfx engine yet.

The immersive map (ShowMap=2) and ShowMapAtDetectMaterial are nice.

**Comment by AquariusPower** [comment]
@iology 

what value you use at `HitIndicator`?
I usually dont play out of the options I most like, and I always use HitIndicator = 4;

Also, if you have a stacktrace may will help on fixing it.

And also the full config file options will also help more because the crash may be related to the interaction between some of the options,
that are probably different from mine as I always use hiteffects and have seen no crash related to it since I did the last commit about it quite a good time ago :)

**Comment by red-kangaroo** [comment]
I'd say remove it from config and make all NPCs restore their equipment.

**Comment by red-kangaroo** [comment]
Resolved by making all NPCs restore their equipped items.
