### ISSUE TITLE
Old saves with same player name got overwritten

### ISSUE THREAD

**Issue by iology** [Attnam/ivan#414]
https://github.com/Attnam/ivan/blob/a5d57a28abf7945ae65edde66e23a11cd2d922d1/Main/Source/game.cpp#L3094-L3128

Is the name length still an issue on Windows? https://github.com/Attnam/ivan/blob/a5d57a28abf7945ae65edde66e23a11cd2d922d1/Main/Source/game.cpp#L3122-L3125

Better naming: `[PlayerName]-[YYYY-mm-dd-HH-MM-SS]`, e.g. Player-2018-07-01-23-30-34

**Comment by AquariusPower** [comment]
Looks good!
Will have to keep the creation time stored in the .sav file I guess, could be a simple festring if troubling to store DtTm.
Would be cool to even show that ctime on the list, but it is already quite bloated :/, may be the selected entry could show it.
I am almost sure will cause no problems on windows.

**Comment by iology** [comment]
Or just append the elapsed seconds since the Unix epoch.

**Comment by iology** [comment]
Solved.
