### ISSUE TITLE
Can't identify rotated piled items

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#415]
I've been play testing 0.53 a lot, and while I **love** most of the changes, one that I really dislike is the rotated piled items.

Often looking at the pile, it's impossible to tell even what type of item it is. Even more difficult when the items are broken. Example, here is a pair of broken gloves:

![phmgni8iesq8lboldlmcqz06f8iwnj_1529270227](https://user-images.githubusercontent.com/2760420/41565896-7af59f92-731e-11e8-8b42-d955684704dd.png)

I think it was a nice idea in theory but should be reverted

**Comment by AquariusPower** [comment]
"rotated piled items." you mean you prefer them rotated randomly or to always keep the default rotation?
Also, from all tests I did, I think some rotations become random by vanilla code, not sure tho.

One problem I couldnt solve yet is, after an item is thrown (when the rotating thrown option is enabled), when it falls on the ground and we step one or more times, it may suddenly rotate once more, and I dont know why, I think it rotates to the vanilla rotation that differs from the last flying/spinning rotation. But I think you didnt throw those gloves :)

btw, could this suffice?
![selection_100](https://user-images.githubusercontent.com/17087075/41573604-ee3bef30-7353-11e8-946e-b16af64caa76.jpg)
it is from a recent commit and is quite tactical as we dont have to waste time on the list in look mode when we should also not move over to avoid certain death :)

**Comment by iology** [comment]
I want to keep equipped items unrotated.

**Comment by AquariusPower** [comment]
@iology 
The main issue I think can be easily seen on the gfx files.
If you pay attention you will see the image sources are rotated not pointing all to the same direction.
The hiteffects code talks (in comments) a lot about that as being quite a problem to it work well.
The good would be to rotate the graphics on both items files to point always to a same direction, as I remember the best direction would be upper right corner.

**Comment by andrewtweber** [comment]
I prefer keeping the default rotation both on the ground and when in inventory/equipped

**Comment by iology** [comment]
Put the lighting angle aside, the original direction is normal, at least not upside down.

**Comment by red-kangaroo** [comment]
I'm not sure what changed, but there is something in the script that allows mirroring/flipping of sprites. It was forbidden for equipment and enabled for eg. sticks. Maybe something was inadvertently changed there?

**Comment by andrewtweber** [comment]
I mostly notice it with gloves and boots, but I also saw a fairysteel helmet that was rotated on its side. That one seemed unintentional to me so maybe all of it is unintentional

**Comment by AquariusPower** [comment]
Btw, I think that items not rotated on battleground should be **optional**.

I still want to see them all _confusedly rotated on the battleground_ as it is more natural, because that increases the variety of the game, and Ivan spirit is about variety and chaos xD

**Comment by andrewtweber** [comment]
Another helmet that's on its side while it's equipped. Looks a bit silly

![screen shot 2019-01-19 at 11 57 18 am](https://user-images.githubusercontent.com/2760420/51430481-900eee80-1be1-11e9-942e-3012c6aeb55e.png)
