### ISSUE TITLE
Prevent golems from appearing in Underwater Tunnel

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#417]
https://attnam.com/posts/29134

**Comment by iology** [comment]
The bamboo golems show up the most for me. I guessed they are fragile but in fact they are too fast, and I should have a striking wand or a lightening wand at hand. (GitHub should let people vote with 💔.)

**Comment by AquariusPower** [comment]
I liked the extra hardcore on UT too, but not so much, and I think it may be a bit complicated to make that optional.
But also, what usually happened was that, I had to run and gather as many items as possible cuz I knew a bonesfile would be ready soon. With many bonesfiles the chances of surviving UT would increase.
May be, we could add a difficulty option to create some hardcore spawns out of their expected places, like a vampire, some golems, werewolf (surviving it and contracting lycantrophy would be awesome early in the game!).

**Comment by AquariusPower** [comment]
may be a material requirement could be the trick,
but I dont think it should be the hardness,
may be the price, as everything magical are pricey.

**Comment by iology** [comment]
A golem is always spawned for the hidden chest.

Give me a slow golem and I can run away.

**Comment by AquariusPower** [comment]
I think their speed are also based on the material they are made of? may be a speed cap.

**Comment by andrewtweber** [comment]
I think this fix definitely improves things. I've still run into some pretty dextrous golems early in GC/TX that will still be troublesome. Might be worth revisiting later
