### ISSUE TITLE
Praying to Silva in the Cathedral Cellar causes infinite loop

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#42]
To be able to pray to Silva in the cellar you first have to go the edge of the map to get out of the area that's dedicated to Valpurus.

**Comment by rvanherel** [comment]
Fixed by this: https://github.com/Attnam/ivan/commit/701561033e34c05cb33f6cb3e1ea7b0ac9eaab17

**Comment by emlai** [comment]
Now I get an `EXC_BAD_ACCESS` in `level::EarthquakesAffectTunnels` when I try to do this.

**Comment by rvanherel** [comment]
Uh oh. Was that when you ran the program?

**Comment by emlai** [comment]
Oops sorry it was just that I forgot to copy the scripts to the right place. It's working now!

**Comment by rvanherel** [comment]
Phew :)
