### ISSUE TITLE
v2() = default?

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#448]
I did this:
`v2() : X(0), Y(0) { };`
was: 
`v2() = default;`

is there some really good  reason to NOT initialize X and Y?
what 'default' does? as is not setting'em to 0 (I tested and in many cases X was like 34875638756 (some huge number)), it is probably not good enough. 
regex to find all possible problematic places w/o this new constructor: `v2 [^=(:]*;`

change applied here: https://github.com/Attnam/ivan/pull/382

**Comment by iology** [comment]
Dunno. But randomness was definitely not intended, I think.

**Comment by AquariusPower** [comment]
I've been testing it a lot w/o problems (the new constructor).
I went thru stackexchange about `= default` but yet nothing convinced me we should keep it.
Something about trivial class  types, I dont get how important that may be yet..

**Comment by red-kangaroo** [comment]
Resolved?
