### ISSUE TITLE
Eating mushroom gives multiple effects.

### ISSUE THREAD

**Issue by Stihdjia** [Attnam/ivan#453]
I just ate a regular mushroom and got levitation, confusion, regeneration, and I think some other effect. Is this intentional?

**Comment by Stihdjia** [comment]
But, but... I need long lasting levitation to teleport Genny without a wand!

**Comment by AquariusPower** [comment]
> teleport Genny without a wand

you throw mushroom to be eaten by it? cool! xD

> so I can go buy a book of Seges

dont eat until near the isle exit :)

> fight more plants before I starve

kiwis are quite feeding actually

> sumo championship

never tried it, I think I need to be bloated right? not sure tho..

> And I need that so I can levitate!

dont we all (irl xD)

**Comment by Stihdjia** [comment]
Not by throwing the mushroom, although I'll have to try that! If at all
possible I usually try to levitate off of New Attnam Island, and enter the
tunnel exit on the other side. Genny gets pushed out of the way and
randomly teleports somewhere else and I'm free to go back and forth between
Attnam and NA at my leisure, while still having plants spawning. This
tactic has however stranded me on the world map to starve multiple times.

**Comment by AquariusPower** [comment]
ahh, that is a code thing that grants the player will always be where he should be, pushing everyone else away, but in this specific case, an exception should be added as the big plant life goal is to block that passage, and it should only be moved by magic, so that trick is a glitch :>

may be, when getting inside tha dungeon, the player could be placed near but not where the big plant is :>

**Comment by Stihdjia** [comment]
Aww OK then, as long as I can still zap her with wands (and now throw her
magic mushrooms ;) )

**Comment by Stihdjia** [comment]
Yeah it looks interesting, I've been wanting to try it out. I've been
getting some crashes on the main branch though and I would like to narrow
down the cause. In both cases I had a Saal'thul, but that's almost
certainly unrelated. (heartbreaking though)

One crash was after returning to human form after fighting Huang Ming Pong
as a werewolf in New Attnam. I lost control of my character, but I was
still in control of *something else* in the sumo house. My vision was still
based on my human character, but whatever I was controlling was not in
sight. I somehow walked out of town as the mystery creature and saw my main
character on the world map, but crashed as soon as I tried to go back into
town.

The autosave was in the world map, recovery option had no effect. (I think
because my real character was in a different location.)

I haven't been sure where to report this, but it was before you guys were
supposed to have fixed that body switch/mirror/cloning bug. The second time
was after that, but with no unusual conditions so I don't know if it was
related.

**Comment by Stihdjia** [comment]
Yeah I tried it with every configuration. No luck.

**Comment by AquariusPower** [comment]
@Stihdjia if you dont mind sharing that savegame (compressed), I may take a look on it :), I will need all the files for that character as the .sav expects them to be created already.

**Comment by AquariusPower** [comment]
I think these lines from game.cpp are strongly related to the issue
```
  SumoWrestling = true;
  character* MirrorPlayer = Player->Duplicate(IGNORE_PROHIBITIONS);
  character* MirrorSumo = Sumo->Duplicate(IGNORE_PROHIBITIONS);
  SetPlayer(MirrorPlayer);
```
something went wrong when it happened,
I think it may not be complicated to simulate the problem again as there is code to duplicate the player,
may be some tries entering sumo may replicate it :>

**Comment by Stihdjia** [comment]
Sure, I uploaded it as "Aenech_Enda.tar.gz" on the IVAN branch under my
name.

I suspect the game autosaved on the world map though, while my actual
character is still in New Attnam.

**Comment by Stihdjia** [comment]
https://github.com/Stihdjia/ivan/blob/master/Aenech_Enda.tar.gz

**Comment by AquariusPower** [comment]
the abort message says the player is missing,
do you remember this happening? (comment from feio.cpp)
```
        /**
         * Backups are a fallback mainly when a crash happens like this:
         *
         * - USER action: you try to enter a new dungeon (so it will be created now)
         *
         * - game action: saves a backup of the current dungeon last save at ".bkp"
         * - game action: saves the current dungeon w/o the player on it at ".tmp" (so if this saving crashes, the corrupted .tmp will just be ignored)
         * - game action: copies the sane ".tmp" to the final filename (and deletes the ".tmp" just after)
         *
         * - game bug: the new dungeon creation fails and crashes.
         *
         * This means: the only file remaining with player data (a player char at dungeon pos) is the .bkp one!!!
         */
```

**Comment by Stihdjia** [comment]
Yeah, I was controlling something I couldn't see and left the town.

This should already be fixed, don't worry about it too much.

**Comment by AquariusPower** [comment]
oh I do... I dont want it happening again to any of us xD
I will code a findPlayer() function to see what happens :)

**Comment by AquariusPower** [comment]
I think you may be running not the latest as this .AutoSave duplicity should be fixed already:
```
Anech_Enda_1532098531.AutoSave.AutoSave.30
Anech_Enda_1532098531.AutoSave.AutoSave.sav
Anech_Enda_1532098531.AutoSave.AutoSave.wm
```
so, there are also 3 older files
```
Anech_Enda_1532098531.AutoSave.30
Anech_Enda_1532098531.AutoSave.sav
Anech_Enda_1532098531.AutoSave.wm
```
that you can safely delete.
Now rename the 3 ones with the dup autosave to the names of the ones deleted.

this branch contains the improved fixer (I will create a PR as soon it is fully working)
https://github.com/AquariusPower/ivan/tree/ImprovedDupPlayerBugFix

That will let you load on the wilderness.
Enter New Attnam.
You will see yourself invisible and a werewolf (both are the player).

Now on the config, enable the dup player bug fix, 
accept "y",
kill the asleep werewolf,
enable again the config option (that is explained on the messages there too),
try to save the game.

There is a final thing I have to fix, the torso of the dup player is not being fixed, it is keeping the item ID=1 it seems...
