### ISSUE TITLE
difficulty modes

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#456]
https://github.com/Attnam/ivan/issues/429#issuecomment-406808096

**Comment by Stihdjia** [comment]
I'm not into it. IVAN is supposed to be brutally unfair.

Lots of people have made their own personal easier versions though.

**Comment by Lum4r** [comment]
It already has Wizard Mode. It's the nature of rougelikes to have two difficulties: Absurdly, Mercilessly Difficult and Cheating.

**Comment by AquariusPower** [comment]
I think balanced is doable (as oposed to impossible or annoying), 
challenging is a must, I think we didnt abbandon Ivan also cuz it is utterly challenging :>

The crafting system I created may make things easier, and that scares me...
so I am trying to make it more difficult, taking time, fumble etc to create things, 
suggestions are welcome.

May be wizard mode suffices already :)

**Comment by AquariusPower** [comment]
@red-kangaroo
> when you can just decide to play in easy mode

that is the most scary thing,
"when we have the option" we may not hold ourselves b4 using it,
and less challenging will make it less memorable too :>

**Comment by red-kangaroo** [comment]
@AquariusPower 

> So, may be wizard mode suffices already :)

Yeah.

**Comment by andrewtweber** [comment]
Doesn't hurt to discuss this every now and then, but it seems like most are agreed to not introduce difficulty modes.
