### ISSUE TITLE
hotkeys limit may be reached soon...

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#462]
practically every key now has a functionality right?
soon we will not be able to add features as hotkeys...

on the crafting system, 
after pressing 'f' we can access sub-functionalities, that methodology could help on incrasing hot-keys,

**SPACE KEY**
so may be, using "SPACE" key, very easy to press by both hands, could open a sub-set of hot-keys and we would instantly have it triplified! 
yes, not doubled because the right part of the keyboard already conflicts with alternative moving key modes and is a "bug" that needs fixing to ppl that prefer them.

So, the second "tab" of hot-keys would allow us do much more :)

**CTRL+**
at the console commands PR, you can access it thru 
```
Ctrl+`
```
but I had to hard-code it so it is not easy to set other Ctrl+ keys...
May be, all new hot-keys could be just Ctrl+... and that would avoid the double press (SPACE, show felist, and a key after), what may be better. But needs implementation.

what u think?

**Comment by red-kangaroo** [comment]
Don't we still have quite a few capital letters left? But I like the idea with Space.

Of course, remappable keybindings would probably be ideal, though probably not that easy to code.

**Comment by AquariusPower** [comment]
may be not that hard either :)
https://github.com/Attnam/ivan/pull/401#issuecomment-408644478

**Comment by andrewtweber** [comment]
As far as I can tell these ones are available:

```
A, B, b, F, f, H, J, j, K, L, N, P, q, R, U, v, x, Y, y
```

While these are in use:

```
a, C, c, D, d, E, e, G, g, h, I, i, k, l, M, m, n, O, o, p, Q, r, S, s, T, t, u, V, W, w, z
```

I think we have enough capital letters as @red-kangaroo says. I'll close this for now. I do like the space idea better than `Ctrl`
