### ISSUE TITLE
crafting vs necromancers

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#472]
crafting has a "split lump" feature that can split corpses (like of bears to be easier to carry a bit)
but... you can split zombies, and that lowers the necromancers threat (if you manage to b4 they get raised).
what lowers the challenge.
**should that feature be limited to non-humanoid corpses?**
or this could be a tactical move?
may be another user config option?

**Comment by red-kangaroo** [comment]
I like it as a tactical option. Make it take a bit of time.

**Comment by AquariusPower** [comment]
it currently takes about 2 turns, time enough for the necromancer to raise the corpse even from our inventory, 
I guess upping it a little bit like 3 or 4 turns would make it more challenging then :). this extra time can be exclusive to humanoid/zombie also.

**Comment by AquariusPower** [comment]
Forgot to close this one.
