### ISSUE TITLE
Moving Linux state dir to user dir

### ISSUE THREAD

**Issue by akien-mga** [Attnam/ivan#493]
I'm working on packaging the current release of IVAN for my Linux distro [Mageia](https://mageia.org).

I've noticed that the buildsystem and `Main/Source/game.cpp` define `GetStateDir()` as pointing to `/var/ivan`, while macOS uses `GetHomeDir()` for that. `GetStateDir()` is then only used to store the `Bones` folder and high score file.

Nowadays using `/var` for game data on Linux is not recommended, only system and server applications should have a need for it. User applications are meant to use `XDG_CONFIG_HOME` (usually `~/.config`) and `XDG_DATA_HOME` (usually `~/.local/share`) for that.

A simple fix for this on Linux would be to drop the `!MAC_APP` code that defines `GetStateDir()` as different from `GetHomeDir()` on non-OSX. And maybe drop `GetStateDir()` to replace it by `GetHomeDir()` directly to simplify the code.

I'd also suggest considering the use of `XDG_DATA_HOME/ivan` on Linux instead of `~/.ivan` (with fallback to its typical value `~/.local/share/ivan` if not defined), but that would break compatibility with existing save games so it might not be wanted. Just know that using `~/.<name>` is now deprecated and that the "good practice" is to use `<name>` folders in `~/.local/share` and/or `~/.config`.

**Comment by akien-mga** [comment]
Well, right after I wrote this I had a quick look at the master branch and I saw #490. This is similar to what I describe, and was done for similar reasons (NixOS packaging), but I would suggest going a step further and not making it an option.

This split between `GetHomeDir()` (which is also used on Linux as `~/.ivan`) and `GetStateDir()` seems unnecessary, and probably the result of incremental changes to this code without re-evaluating the choices made two decades ago when `/var` was indeed a place where apps wrote their state (actually `/var/games` for games).

**Comment by iology** [comment]
I think `~/.local/share` is not a good place unless IVAN is also installed at `~/.local`, and normally save files should not be shared.

We can first detect XDG_CONFIG_HOME on linux, if no then fall back to HOME.

Should also give a notice about this change while running cmake.

/ping #495
/cc @Attnam thoughts?

**Comment by akien-mga** [comment]
> I think ~/.local/share is not a good place unless IVAN is also installed at ~/.local, and normally save files should not be shared.

No, `~/.local/share` is the place where applications put their runtime data. No application is installed there, unless it's an application that installs it at runtime (e.g. you have a downloader in `/usr/bin/get-my-game` which will download and install the game in `~/.local/share/my-game`). Keep in mind that `~` *is* `HOME`. This location is not shared with other users (I'm not the one who chose its name -- it just mirrors `/usr/share` which is the system-wide location where applications are meant to install their read-only data).

See the specification: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by akien-mga** [comment]
Note that the main point of this issue is to drop `GetStateDir()` to replace it by `GetHomeDir()` and have everything in `~/.ivan` on Linux instead of splitting some data in the often read-only `/var/ivan`.

**Comment by iology** [comment]
Yup, the inconsistent interpretations of "read-only" about `/usr/share` and `~/.local/share` make me slightly insane. Saves, bone files, high scores are not configs, so it seems `~/.ivan` is the best place (but adds to the bloat of the 1st level of $HOME).

**Comment by akien-mga** [comment]
> Saves, bone files, high scores are not configs, so it seems ~/.ivan is the best place (but adds to the bloat of the 1st level of $HOME).

Well, currently `~/.ivan` already exists, so bone files and high scores can move there.

To reduce the bloat of the 1st level of $HOME, `GetHomeDir()` could be moved from `~/.ivan` to `~/.local/share/ivan` on Linux (with the aforementioned caveat of compat loss with previous versions of the game).

**Comment by freepotion** [comment]
> See the specification: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I found a name there that made me a little nervous :smiling_imp: It's a specification, not a standard, right? I mean, we don't have to follow it?

In my new [PR](https://github.com/Attnam/ivan/pull/495) everything will remain as it is (in `~/.ivan`). The final decision is up to IVAN devs.

**Comment by freepotion** [comment]
> See the specification: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

It's a specification, not a standard, right? I mean, we don't have to follow it?
In my new PR everything will remain as is (in ~/.ivan). Anyway, the final decision is up to IVAN devs. :sunglasses:

**Comment by red-kangaroo** [comment]
This is resolved, right?

**Comment by Soundtoxin** [comment]
Just found this issue searching for "XDG" in hopes someone had already suggested moving from ~/.ivan to one of the XDG locations like ~/.local/share. One thing that might not have been made clear in the discussion here earlier is that the standard also defines variables, so you could default to ~/.ivan anyway and let people move it elsewhere, or default to the new spot if nothing exists in the old one / let people override and use the old spot. It really would be nice to have less stuff pollution the home directory itself.
