### ISSUE TITLE
Arrow keys enter letters in string questions

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#50]
Pressing arrow keys while in a string question causes random letters to be entered in the text field.

**Comment by eldios** [comment]
What is the desired behavior here? Should the character move? Should the question be canceled or the keystrokes simply ignored?

**Comment by andrewtweber** [comment]
Ignoring is fine, or if the cursor can be moved left/right but that would be more difficult I imagine

**Comment by emlai** [comment]
Yes ignoring is fine imo. Also moving left/right is actually quite simple to implement. Just keep the text as a separate buffer and render the cursor on top of that.
