### ISSUE TITLE
compiling on linux: EXTRA_DIST sources issue

### ISSUE THREAD

**Issue by sshilovsky** [Attnam/ivan#51]
charset.o:(.rodata._ZTV8punisher[_ZTV8punisher]+0x908): undefined reference to `humanoid::SetFireToBodyPart()'

It looks like sources mentioned in Main/Source/Makefile.am EXTRA_DIST variable (including human.cpp which contains the above method) are not compiled and linked together.

human.o is not built as other object files corresponding to EXTRA_DIST files. While ivan_SOURCES files are compiled by the time of ld exec.

**Comment by sshilovsky** [comment]
It's all right in 0.50.3.

Sorry for that, different download sources are really confusing about outdated and recent versions.

**Comment by emlai** [comment]
Yeah I actually remember fixing that in https://github.com/Attnam/ivan/commit/d330ce142492010fa56f32a34e460a4d2d6e647b. 

`humanoid::SetFireToBodyPart()` was just missing a definition when compiled without `-DWIZARD` mode. Good to know you got it working. :smile:

**Comment by andrewtweber** [comment]
@sshilovsky which different download sources? Do you mean Github vs. http://attnam.com ?

**Comment by Clawzfire** [comment]
>missing a definition when compiled without `-DWIZARD` mode.

This reminds me that `-DWIZARD` should probably be the default. There's not really much reason to disable wizard mode.

**Comment by emlai** [comment]
@Clawzfire Actually, I think it should _not_ be enabled by default. It's a huge spoiler for new players and only useful for debugging purposes.

**Comment by eldios** [comment]
+1 to disabling wizard mode by default, though it'll be nice one day to have a way to play a mage character

**Comment by sshilovsky** [comment]
@andrewtweber Yes. The Version_History wiki page at attnam.com was linked to 0.50.2 directly. This wiki page was actually the way I knew that the development process had moved here. There are also many other places (e.g. ivan.sourceforge.net) that do not even mention github and versions >0.50, which I understand you might have no access to, but they are even more confusing.

**Comment by andrewtweber** [comment]
Thanks, that's very helpful! Yes, the sourceforge page is out of our control and unfortunately the original devs have long disappeared. I'll see if I can update Attnam.com to pull from Github's API so that it is always up to date.
