### ISSUE TITLE
Cutting web

### ISSUE THREAD

**Issue by iology** [Attnam/ivan#515]
@AquariusPower

Since this action takes only one turn and is uninterruptible, is it okay to not actually switch weapons? This forces me to manually restore the original weapons.

**Comment by AquariusPower** [comment]
That is a missing feature! if I am not wrong, it got a bit complex to make it work and I had other priorities, btw to use a pick-axe was the code reference I used.
I will take a look on that, it annoys me too..

**Comment by AquariusPower** [comment]
https://github.com/Attnam/ivan/pull/517/
I did basic tests on it and is working (least for the nasty "rare" (as getting stuck in the web is coded to happen but rarely) bug https://github.com/Attnam/ivan/issues/516)

**Comment by andrewtweber** [comment]
This is complete right?
