### ISSUE TITLE
Can't douse fire on item that is already covered in liquid

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#526]
For example I have a boot that is currently covered in blood, but I'm not given the option to select it to dip it into a can of water.

**Comment by AquariusPower** [comment]
Things being set on fire, if already wet, **should become dry** and not be set on fire after that single explosion.
A tactic could be to wet (at a fountain) all burnable equipment before trying to open trapped doors or facing other granted explosion situation.
But this will make things easier...

**Comment by andrewtweber** [comment]
Hm actually I think that is already in place. Well, the fire isn't **prevented**, but those items that were covered in blood extinguished very quickly and didn't get damaged. That works for me.
