### ISSUE TITLE
Change blue status strings color to a more readable one

### ISSUE THREAD

**Issue by eldios** [Attnam/ivan#53]
I propose to change the dark blue color of the status string (burdened, stressed, etc..) to a more readable one. Even shifting it to a lighter blue by a little would probably do the trick imo.

**Comment by emlai** [comment]
I agree. Would something like this be good?
<img width="149" alt="screen shot 2015-07-17 at 19 31 13" src="https://cloud.githubusercontent.com/assets/7543552/8752180/529aecde-2cbb-11e5-9896-3f3c8c987578.png">
Original color for comparison:
<img width="152" alt="screen shot 2015-07-17 at 19 34 58" src="https://cloud.githubusercontent.com/assets/7543552/8752189/5db4b578-2cbb-11e5-85a3-d507672d44eb.png">
Or even lighter?

**Comment by Clawzfire** [comment]
That one looks pretty good to me. Too much lighter and it might start to look a bit strange.

**Comment by eldios** [comment]
definitely better.
