### ISSUE TITLE
Wand of webbing is not hostile

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#530]
I zapped Richel Decos with a wand of webbing and he ignored it.

Should be considered hostile I think. It's basically a trap - I don't believe planting land mines or bear traps will trigger a hostile reaction either, but I figure those can be done more surreptitiously vs. zapping somebody with sticky spider webs.

Anybody thoughts?

**Comment by AlexMooney** [comment]
It's pretty nice to be able to use a wand to support your allies with little danger of them hating you.  But it wouldn't be expected, so it's not like folks know to take advantage of it.  Hostile act, I suppose.

**Comment by andrewtweber** [comment]
Hm.. possible compromise, if you hit an **ally** with a wand of webbing, it does nothing, but if you hit a **neutral** they interpret it as an attack?

**Comment by AlexMooney** [comment]
I think that would be a welcome addition.  It's probable that such a mechanic could be useful in other situations too.
