### ISSUE TITLE
TX entrance blocked off

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#541]
Well this is awkward :D Luckily I had a pickaxe and could dig through the house. This could've been game-ending though if I didn't.

An easy solution would probably be to move those guards up one spot to be next to the wall instead of in front of it.

![tx](https://user-images.githubusercontent.com/2760420/53688527-00457f80-3d0b-11e9-973f-1eaa2c9fec12.png)

**Comment by AquariusPower** [comment]
I think is this, XinrochTomb.dat line 164:

    Square, Pos 28, 51; { Character = guard(TOMB_ENTRY); }
    Square, Pos 32, 51; { Character = guard(TOMB_ENTRY); }

could be this then

    Square, Pos 29, 50; { Character = guard(TOMB_ENTRY); }
    Square, Pos 31, 50; { Character = guard(TOMB_ENTRY); }

**Comment by andrewtweber** [comment]
I would also want to expand the opening to 5 spaces. That way if the guards are standing inside the entrance, there are still 3 spaces for the player to pass through.

or maybe we could add a little nook for them to stand in. Something like this:

![53688527-00457f80-3d0b-11e9-973f-1eaa2c9fec12](https://user-images.githubusercontent.com/2760420/53768601-f0f73b00-3e9e-11e9-9f69-7c17d5f8507e.png)

**Comment by AquariusPower** [comment]
I tried to find 3 spaces (the entrance) on that file, but found none, not sure how it is created
I guess also, if we put one guard above and another below, it "may grant" that house wont spawn blocking the entrance, and also allow we to pass thru

**Comment by iology** [comment]
Another solution: mark the floor tiles under the guards' feet as a placeholder.

```diff
 GTerrainMap
 {
   Pos = 4,5;
   Size = 33,31;
   Types
   {
     # = BLACK_GRANITE solidterrain(FLOOR) { IsInside = true; }
     - = BLACK_GRANITE solidterrain(FLOOR) { IsInside = true; }
     | = OCTIRON solidterrain(FLOOR) { IsInside = true; }
     % = RUBY solidterrain(FLOOR) { IsInside = true; }
+    @ = SNOW solidterrain(SNOW_TERRAIN) { IsPlaceholder = true; }
   }
 }
```

**Comment by andrewtweber** [comment]
@iology that would be perfect

**Comment by fejoa** [comment]
There's also #547 which gives us this solution:

![clipboard01](https://user-images.githubusercontent.com/6005108/53778176-bf46a880-3f60-11e9-82e3-d6d569e8de05.png)

**Comment by iology** [comment]
One more solution: increase the minimum distance between rooms (fixed value or configurable).
