### ISSUE TITLE
Weapon swap lets you steal back sold items

### ISSUE THREAD

**Issue by kristofferbergstrom** [Attnam/ivan#555]
If the player has more than one weapon swap config, and you swap to an item that's been dropped at the player's feet, the item is instantly picked up and equipped. This doesn't seem take the item's current ownership into account, and can be used to steal back any item that has been donated or sold to a shop.

**Comment by AquariusPower** [comment]
https://github.com/Attnam/ivan/blob/master/Main/Source/cmdswapweap.cpp#L406

I think it could be solved with `!it->GetRoom()` as
`if(hasItem(iv,it) || (it->GetSquareUnder()==Char->GetSquareUnder() && !it->GetRoom()) ) {`
(based on pickup command code) can someone test it?

**Comment by red-kangaroo** [comment]
This should be fixed now.
