### ISSUE TITLE
Make burning food uneatable

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#56]
There should probably be some warning message when you try to eat food that is currently burning. (At least in human form and other forms that don't like fire.)

Or/and there could be a chance that doing so will set your head on fire.

**Comment by rvanherel** [comment]
I feel responsible for this. I think I will have some time this week to look into it.

**Comment by andrewtweber** [comment]
Closing but with the note that in the future we may have monster types that like fire and are ok with consuming burning items
