### ISSUE TITLE
Migrate LGTM.com installation from OAuth to GitHub App

### ISSUE THREAD

**Issue by LGTM-badger** [Attnam/ivan#567]
Hi There,

This project is still using an old implementation of LGTM's automated code review, which has now been disabled. To continue using automated code review, and receive checks on your Pull Requests, please [install the GitHub App](https://github.com/apps/lgtm-com/installations/new) on this repository.

Thanks,
The LGTM Team

**Comment by andrewtweber** [comment]
@fejoa I set it up, but wasn't sure if you needed/wanted to clean up the "old implementation"

**Comment by fejoa** [comment]
I don't think we need to keep the old implementation, so I guess it can just be cleaned up.
