### ISSUE TITLE
Crashes when equipping weapon

### ISSUE THREAD

**Issue by travankor** [Attnam/ivan#568]
Ivan  57 crashes whenever I equip a weapon. 
OS: GNU/Linux

[Valgrind](https://waifupaste.moe/raw/bBy.txt)

Let me know if you need some other debug info.

**Comment by AquariusPower** [comment]
Hi! 
Could you paste here the usual 
simple and short stacktrace with the 
nice game error message (if the game was able to prepare that)?

Also, it happens for that savegame only or for all savegames (other heroes)?

Have you tried w/o Valgrind, I remember, with other debuggers/profilers that some weird stuff could happen only when using them, but that experience is not using Ivan was in java or c++ long time ago.

**Comment by travankor** [comment]
Well, looks like I completely forgot about this...

Anyways, this bug is gone in ivan v58
