### ISSUE TITLE
teardown.wav is using the old heart beat sound? :)

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#581]
cut a web and thought got badly hurt?!?... but not!
I see the new heartbeat.wav is better (and bigger)
not really an issue, just got used to the old sound probably :>

**Comment by red-kangaroo** [comment]
@AquariusPower Please call me out on any changes you don't like. 🙂 I'm making tweaks based on what I find appropriate, but I wouldn't want to change your work in a way you don't approve of.

**Comment by red-kangaroo** [comment]
And yes, I reused the old bleedsbadly as tearing sound, because it sounds to me like something giving way. ☺️

**Comment by AquariusPower** [comment]
as I remember, there was no sound to tearing web and there is a lot of new sounds that is very good (I saw even the ones not used yet at .devsPrefs), 
but I think the most important is the feedback of most players at Attnam.com,
anyway, I liked most of the changes, great work! (couldn't reach Aslona yet tho)

btw, when creating a new dungeon level, it tried to use an old bones file and aborted with some error I don't remember which. I think the versions haven't been updated? would be good to do so I guess :)

**Comment by red-kangaroo** [comment]
Yeah, I might have forgotten to update the version number. 😐

**Comment by AquariusPower** [comment]
I added 3 new sounds to teardown, (I was going to destroy some cloth (irl) but instead I used a paper and some editing in audacity, felt ok), at:
https://github.com/AquariusPower/ivan/tree/SomeFixes1234
(I didnt reuse the current sound on the config as was too much different) I think this sound could be better tho, may be based on cloth.
