### ISSUE TITLE
Compiling in Ubuntu 20.04 with an SDL2 error

### ISSUE THREAD

**Issue by jason-mehmel** [Attnam/ivan#625]
I'm trying to compile IVAN from the releases, following the directions in the INSTALL guide.

When I get to **cmake ~/Downloads/Attnam-ivan-87f4a33/**

I get what is below! I've got all the SDL2 libraries that I can see in my repositories, so I'm not sure what I'm missing!

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SDL2 (missing: SDL2_mixer_LIBRARY SDL2_mixer_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2.cmake:197 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  FeLib/CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jason/Downloads/Attnam-ivan-87f4a33/build/CMakeFiles/CMakeOutput.log".
See also "/home/jason/Downloads/Attnam-ivan-87f4a33/build/CMakeFiles/CMakeError.log".

**Comment by fejoa** [comment]
Have you installed `SDL2_mixer` on your build machine?

`apt-get install libsdl2-mixer-2.0-0`

**Comment by jason-mehmel** [comment]
I thought I had them, but I didn't have the libsdl2-mixer-dev installed.

I installed that one, and it compiled! Thank you for the help!
