### ISSUE TITLE
Crashing after kamikaze dwarf's death

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#65]
Reported on IRC

    19:44 <Jinxed> 0.50.2 crashed on kamikaze dwarf's death and now crashes on start ever since then
    19:46 <Jinxed> Apparently it is 0.50.3 actually

**Comment by emlai** [comment]
Might be the same as #57? Although that "now crashes on start ever since then" hasn't happened to me, so it might be something else (but possibly related) after all.

Hope that guy comes back so we can ask more information.

**Comment by andrewtweber** [comment]
Ah I forgot about that issue. Probably the same thing.

**Comment by rvanherel** [comment]
What guy?

**Comment by emlai** [comment]
This was most likely fixed in #66, so closing this. We can reopen if the issue shows up again.
