### ISSUE TITLE
OSX compilation issues for C++11

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#68]
For OSX to compile C++ 11

- `clang++` needs to be used instead of `g++`
- This flag needs to be added to the compiler: `-std=gnu++11`

I wasn't sure how to safely make those changes, so if somebody else could for me then I can try compiling.

**Comment by emlai** [comment]
We could add [`ax_cxx_compile_stdcxx_11`](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_11.html) to the project, or simply put the flag (either `-std=c++11` (standard-conforming mode) or `-std=gnu++11` (with extensions)) to the compilation flags in `configure.ac`.

**Comment by andrewtweber** [comment]
I'll try those tomorrow (don't have my work computer today) and submit a pull request if it works. Thanks, I've never really worked with configure files before

**Comment by andrewtweber** [comment]
Well I was hoping to learn something new (how to work with configure and Makefiles) but I can't figure this thing out.

First tried to add the macro, then gave up and just tried to add `-std=c++11` to CFLAGS. But now after I run `autoconf` to regenerate the `configure` file, when I type `make` it gives this error:

    CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.15 
    /bin/sh: aclocal-1.15: command not found
    make: *** [aclocal.m4] Error 127

Even checking out the repository and starting over doesn't help, I have to remove the entire folder and clone the repo again.

**Comment by emlai** [comment]
Sounds like you have to install `aclocal`

**Comment by andrewtweber** [comment]
Thanks! Compiles on OSX without a hitch now. Sorry, I had tried your suggestions but wasn't able to fix them myself.

**Comment by emlai** [comment]
NP :)
