### ISSUE TITLE
Print Screen funtion in Windows crashes the game

### ISSUE THREAD

**Issue by fejoa** [Attnam/ivan#76]
An error comes up stating: 

Can't open Scrshot/Scrshot000.bmp for output!

**Comment by fejoa** [comment]
fixed by doing this https://github.com/Attnam/ivan/commit/0c3b2ce9d67e626e77f74ca4d430a78edbae6b2c

**Comment by emlai** [comment]
Shouldn't [this line](https://github.com/Attnam/ivan/blob/351b4c0530e84c5aa4d9f026aefd95fae664a5d3/Main/Source/game.cpp#L244) create the `Scrshot` directory if it doesn't exist?

**Comment by fejoa** [comment]
The game crashes when you take a screenshot on first boot-up, on the menu screen. Not likely to affect many users...
