### ISSUE TITLE
Search engine optimization

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#79]
I think this repository could be made more searchable.

For example, searching GitHub for C++ repositories with the keyword "roguelike" doesn't find this repository. (The search only seems to look for the term in the repository name and description.) This could be fixed by changing the description to e.g.

> Continuation of the Iter Vehemens ad Necem graphical roguelike by members of http://attnam.com

or something similar. If that's too long, maybe the "members of" and/or "graphical" could be dropped.

Opinions? Any other ideas to make this repository more findable via search engines?

---

On a related note, when the repository appears in the search, it looks like this:

<img width="459" alt="" src="https://cloud.githubusercontent.com/assets/7543552/12053275/0e9a362e-af20-11e5-95a7-8194bdef5307.png">

Notice how the website is missing at the end. This is not a big deal, but the fix is trivial: simply move the URL from the website field to the description field. It will still be highlighted and clickable.

**Comment by andrewtweber** [comment]
Ah, I didn't know it would still be clickable in the description. Good suggestion, I updated
