### ISSUE TITLE
New movement algorithm causes allies to "run away" from you.

### ISSUE THREAD

**Issue by Clawzfire** [Attnam/ivan#87]
Since #46 was introduced allies will move away from the player when you attempt to follow them, which can make ending up next to them (eg for sci-talking) much more difficult. They also seem to never wander into spaces adjacent to the player if you're standing still.

Allies set to follow should stick around the player more so that you can chat with them.

**Comment by emlai** [comment]
Related: #70

**Comment by emlai** [comment]
Does #98 fix this?
